# Generated by Django 2.2.13 on 2020-12-04 07:18

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToActionSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', wagtail.core.fields.StreamField([('external_link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())], icon='link')), ('internal_link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock())], icon='link'))])),
            ],
        ),
    ]
