# Generated by Django 3.2.12 on 2022-08-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="menusnippetlink",
                    name="link_page",
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="menusnippetlink",
                    name="snippet",
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="LinkGroupLink",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="LinkGroupLink",
                    table="core_linkgrouplink",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="LinkGroupSnippet",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="LinkGroupSnippet",
                    table="core_linkgroupsnippet",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="MenuSnippet",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="MenuSnippet",
                    table="core_menusnippet",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="MenuSnippetLink",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="MenuSnippetLink",
                    table="core_menusnippetlink",
                ),
            ],
        ),
    ]
