# Generated by Django 3.2.18 on 2023-05-02 02:33

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmappage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Intro"),
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="item",
            name="publish",
        ),
        migrations.RenameModel(
            old_name="Item",
            new_name="MilestoneItem",
        ),
        migrations.AlterModelOptions(
            name="milestoneitem",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "roadmap milestone item",
                "verbose_name_plural": "roadmap milestone items",
            },
        ),
    ]
