# Generated by Django 3.2.18 on 2023-04-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0002_roadmappage"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="sponsorship_url",
            field=models.URLField(blank=True, verbose_name="Sponsorship URL"),
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["sort_order", "number"],
                "verbose_name": "roadmap item",
                "verbose_name_plural": "roadmap items",
            },
        ),
    ]
