# Generated by Django 5.0.9 on 2024-11-27 22:16

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0004_alter_roadmappage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmappage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 1),
                    ("text_and_media", 10),
                    ("headline", 14),
                    ("highlight", 17),
                    ("teaser", 21),
                    ("icon_bullets", 26),
                    ("cards", 31),
                    ("logo_cards", 37),
                    ("cta", 38),
                    ("standalone_cta", 40),
                    ("standalone_quote", 42),
                    ("multiple_quotes", 45),
                    ("get_started_block", 46),
                    ("sign_up_form", 47),
                    ("comparison_table", 50),
                    ("logos", 54),
                    ("video", 56),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "ol",
                                "ul",
                                "link",
                                "document",
                            ],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.embeds.blocks.EmbedBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    5: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "CTA text", "max_length": 255, "required": False},
                    ),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "CTA page", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "CTA URL", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 6), ("cta_page", 7), ("cta_url", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 2),
                                ("embed", 3),
                                ("image_on_right", 4),
                                ("heading", 5),
                                ("description", 5),
                                ("cta", 9),
                            ]
                        ],
                        {},
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    12: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("arrow-alt", "Arrow alt"),
                                ("arrow-in-circle", "Arrow in circle"),
                                ("arrow-in-square", "Arrow in square"),
                                ("arrows", "Arrows"),
                                ("blog", "Blog"),
                                ("bread", "Bread"),
                                ("briefcase", "Briefcase"),
                                ("building", "Building"),
                                ("calendar", "Calendar"),
                                ("code-file", "Code File"),
                                ("document", "Document"),
                                ("envelope", "Envelope"),
                                ("explanation", "Explanation"),
                                ("eye", "Eye"),
                                ("flame", "Flame"),
                                ("friends", "Friends"),
                                ("github", "Github"),
                                ("handshake", "Handshake"),
                                ("heart", "Heart"),
                                ("history", "History"),
                                ("id-card", "ID Card"),
                                ("image", "Image"),
                                ("knife-fork", "Knife Fork"),
                                ("leaf", "Leaf"),
                                ("location-pin", "Location Pin"),
                                ("map", "Map"),
                                ("magnifying-glass", "Magnifying Glass"),
                                ("money", "Money"),
                                ("moon", "Moon"),
                                ("one-two-steps", "One Two Steps"),
                                ("padlock", "Padlock"),
                                ("paper-plane", "Paper Plane"),
                                ("paper-stack", "Paper Stack"),
                                ("pen-checkbox", "Pen Checkbox"),
                                ("person-in-tie", "Person in Tie"),
                                ("python", "Python"),
                                ("question-mark-circle", "Question Mark Circle"),
                                ("quotes", "Quotes"),
                                ("release-cycle", "Release Cycle"),
                                ("roadmap", "Roadmap"),
                                ("rocket", "Rocket"),
                                ("rollback", "Rollback"),
                                ("slack", "Slack"),
                                ("speech-bubble", "Speech Bubble"),
                                ("sun-cloud", "Sun Cloud"),
                                ("table-tennis", "Table Tennis"),
                                ("tree", "Tree"),
                                ("wordpress", "Wordpress"),
                                ("world", "World"),
                            ],
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 11),
                                ("sub_heading", 12),
                                ("intro", 12),
                                ("cta", 9),
                                ("icon", 13),
                                ("dark_background", 4),
                            ]
                        ],
                        {},
                    ),
                    15: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 15),
                                ("description", 12),
                                ("image", 2),
                                ("image_on_right", 4),
                                ("meta_text", 16),
                                ("meta_icon", 13),
                                ("cta", 9),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["blog.BlogPage"], "required": False},
                    ),
                    19: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    20: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Subheading for external link", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 18),
                                ("url_chooser", 19),
                                ("image_for_external_link", 2),
                                ("heading_for_external_link", 12),
                                ("subheading_for_ext_link", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("arrow-alt", "Arrow alt"),
                                ("arrow-in-circle", "Arrow in circle"),
                                ("arrow-in-square", "Arrow in square"),
                                ("arrows", "Arrows"),
                                ("blog", "Blog"),
                                ("bread", "Bread"),
                                ("briefcase", "Briefcase"),
                                ("building", "Building"),
                                ("calendar", "Calendar"),
                                ("code-file", "Code File"),
                                ("document", "Document"),
                                ("envelope", "Envelope"),
                                ("explanation", "Explanation"),
                                ("eye", "Eye"),
                                ("flame", "Flame"),
                                ("friends", "Friends"),
                                ("github", "Github"),
                                ("handshake", "Handshake"),
                                ("heart", "Heart"),
                                ("history", "History"),
                                ("id-card", "ID Card"),
                                ("image", "Image"),
                                ("knife-fork", "Knife Fork"),
                                ("leaf", "Leaf"),
                                ("location-pin", "Location Pin"),
                                ("map", "Map"),
                                ("magnifying-glass", "Magnifying Glass"),
                                ("money", "Money"),
                                ("moon", "Moon"),
                                ("one-two-steps", "One Two Steps"),
                                ("padlock", "Padlock"),
                                ("paper-plane", "Paper Plane"),
                                ("paper-stack", "Paper Stack"),
                                ("pen-checkbox", "Pen Checkbox"),
                                ("person-in-tie", "Person in Tie"),
                                ("python", "Python"),
                                ("question-mark-circle", "Question Mark Circle"),
                                ("quotes", "Quotes"),
                                ("release-cycle", "Release Cycle"),
                                ("roadmap", "Roadmap"),
                                ("rocket", "Rocket"),
                                ("rollback", "Rollback"),
                                ("slack", "Slack"),
                                ("speech-bubble", "Speech Bubble"),
                                ("sun-cloud", "Sun Cloud"),
                                ("table-tennis", "Table Tennis"),
                                ("tree", "Tree"),
                                ("wordpress", "Wordpress"),
                                ("world", "World"),
                            ]
                        },
                    ),
                    23: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 22),
                                ("heading", 11),
                                ("description", 23),
                                ("cta", 9),
                            ]
                        ],
                        {},
                    ),
                    25: ("wagtail.blocks.ListBlock", (24,), {}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_bullets", 25)]],
                        {"icon": "rectangle-list"},
                    ),
                    27: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    28: ("wagtail.blocks.TextBlock", (), {"max_length": 50}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 11),
                                ("description", 27),
                                ("meta_icon", 22),
                                ("meta_text", 28),
                                ("cta", 9),
                            ]
                        ],
                        {},
                    ),
                    30: ("wagtail.blocks.ListBlock", (29,), {}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("cards", 30)]],
                        {"group": "Cards", "icon": "table-list"},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 255},
                    ),
                    34: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 33),
                                ("description", 27),
                                ("meta_icon", 22),
                                ("meta_text", 28),
                                ("logo", 34),
                                ("cta_page", 7),
                                ("cta_url", 8),
                            ]
                        ],
                        {},
                    ),
                    36: ("wagtail.blocks.ListBlock", (35,), {}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 32), ("cards", 36)]],
                        {"group": "Cards", "icon": "images"},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 6), ("cta_page", 7), ("cta_url", 8)]],
                        {"group": "Call to action"},
                    ),
                    39: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "label": "Short description",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("cta", 9), ("description", 39)]],
                        {"group": "Call to action"},
                    ),
                    41: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["link"], "required": True},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 5), ("author", 41), ("author_image", 2)]],
                        {"group": "Quotes"},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 5), ("author", 41), ("author_image", 2)]],
                        {},
                    ),
                    44: ("wagtail.blocks.ListBlock", (43,), {"min_num": 2}),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("quotes", 44)]],
                        {"group": "Quotes"},
                    ),
                    46: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.GetStartedSnippet",),
                        {
                            "icon": "table-list",
                            "template": "patterns/components/streamfields/get_started_block/get_started_block.html",
                        },
                    ),
                    47: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.SignupFormSnippet",),
                        {
                            "icon": "envelope-open-text",
                            "template": "patterns/components/streamfields/sign_up_form_block/sign_up_form_block.html",
                        },
                    ),
                    48: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 23), ("image", 2)]],
                        {"max_num": 1, "required": False},
                    ),
                    49: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("content", 48)]],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("comparison_table", 49)]],
                        {},
                    ),
                    51: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    52: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    53: ("wagtail.blocks.ListBlock", (52,), {}),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 51), ("logos", 53)]],
                        {"group": "Logos"},
                    ),
                    55: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"required": False},
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 51), ("video", 55), ("embed", 3)]],
                        {},
                    ),
                },
            ),
        ),
    ]
