# Generated by Django 6.0.2 on 2026-04-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roadmap", "0006_add_wide_image_block"),
    ]

    operations = [
        migrations.RenameField(
            model_name="milestoneitem",
            old_name="sponsorship_url",
            new_name="cta_url",
        ),
        migrations.AlterField(
            model_name="milestoneitem",
            name="cta_url",
            field=models.URLField(
                blank=True,
                verbose_name="Call to Action URL",
                help_text="Custom URL to use for the 'Sponsor/Contribute' labels",
            ),
        ),
    ]
