# Generated by Django 3.2.16 on 2022-10-04 12:57

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks

import wagtailio.services.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicespage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        form_classname="full title", required=True
                                    ),
                                ),
                                (
                                    "icon",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("astronaut", "Astronaut"),
                                            ("cloud", "Cloud"),
                                            ("money-check", "Money check"),
                                            ("tools", "Tools"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "section_media",
                                    wagtailio.services.blocks.SectionMediaBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "section_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Section image is used as a fallback when no media is defined.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "section_image_caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Rendered below the image/media",
                                        label="Section image/media caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "subheading",
                                                wagtailio.services.blocks.SubheadingBlock(),
                                            ),
                                            (
                                                "divider",
                                                wagtailio.services.blocks.DividerBlock(),
                                            ),
                                            (
                                                "paragraph",
                                                wagtail.blocks.RichTextBlock(
                                                    features=[
                                                        "bold",
                                                        "italic",
                                                        "link",
                                                        "ul",
                                                        "ol",
                                                    ]
                                                ),
                                            ),
                                            (
                                                "cards",
                                                wagtailio.services.blocks.CardsBlock(),
                                            ),
                                            (
                                                "link_button",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "lead_text",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Text leading up the action text of the button.",
                                                                max_length=50,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "action_text",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Emphasised text for the button action.",
                                                                max_length=50,
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.blocks.URLBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "quote",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "text",
                                                            wagtail.blocks.TextBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "source",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "reference",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Additional information about the source. E.g. a persons job title and company.",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
