# Generated by Django 2.2.13 on 2021-03-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_add_plain_services_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
