# Generated by Django 2.2.13 on 2021-03-12 02:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicespage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StreamBlock([('title', wagtail.core.blocks.CharBlock(required=True))]))], blank=True, null=True),
        ),
    ]
