# Generated by Django 5.1.4 on 2024-12-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_servicespage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicespage",
            name="intro",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
