# Generated by Django 2.2.13 on 2021-03-12 03:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_section_block_as_struct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(form_classname='title', required=True)), ('content', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(max_length=250))], required=False))]))], blank=True, null=True),
        ),
    ]
