# Generated by Django 2.2.13 on 2021-03-12 03:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_section_content_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(form_classname='full title', required=True)), ('content', wagtail.core.blocks.StreamBlock([('subheading', wagtail.core.blocks.CharBlock(form_classname='full', max_length=250, template='services/blocks/subheading.html'))], form_classname='full', required=False))]))], blank=True, null=True),
        ),
    ]
