# Generated by Django 2.2.13 on 2021-03-25 08:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailio.services.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_fix_num_sections_to_four'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(form_classname='full title', required=True)), ('section_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('section_image_caption', wagtail.core.blocks.CharBlock(required=False)), ('content', wagtail.core.blocks.StreamBlock([('subheading', wagtailio.services.blocks.SubheadingBlock()), ('divider', wagtailio.services.blocks.DividerBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul', 'ol'])), ('cards', wagtailio.services.blocks.CardsBlock()), ('link_button', wagtail.core.blocks.StructBlock([('lead_text', wagtail.core.blocks.CharBlock(help_text='Text leading up the action text of the button.', max_length=50, required=False)), ('action_text', wagtail.core.blocks.CharBlock(help_text='Emphasised text for the button action.', max_length=50, required=True)), ('link', wagtail.core.blocks.URLBlock(required=True))])), ('quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(required=True)), ('source', wagtail.core.blocks.CharBlock(required=True)), ('reference', wagtail.core.blocks.CharBlock(help_text='Additional information about the source. E.g. a persons job title and company.', required=False))]))], required=False))]))], null=True),
        ),
    ]
