# Generated by Django 5.1.6 on 2025-07-01 19:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0017_drop_obsolete_alternative_text'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagtailSpaceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, help_text='Description of this page as it should appear when shared on social networks, or in Google results', max_length=255, verbose_name='Meta description')),
                ('heading', models.TextField(blank=True, verbose_name='Heading')),
                ('event_date_subhead', models.TextField(blank=True, verbose_name='Event date')),
                ('tagline', models.TextField(blank=True, verbose_name='Tagline')),
                ('cta', wagtail.fields.StreamField([('cta', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'CTA text', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'CTA page', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'CTA URL', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('cta_page', 1), ('cta_url', 2)]], {})})),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Body')),
                ('social_image', models.ForeignKey(blank=True, help_text="Image to appear alongside 'Meta description', particularly for sharing on social networks", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.wagtailioimage', verbose_name='Meta image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
