# Generated by Django 5.1.6 on 2025-07-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0017_drop_obsolete_alternative_text"),
        ("wagtailspace", "0002_wagtailspaceindexpage_listing_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailspacepage",
            name="listing_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to display along with summary, when this page is linked from elsewhere in the site.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.wagtailioimage",
            ),
        ),
        migrations.AddField(
            model_name="wagtailspacepage",
            name="listing_intro",
            field=models.TextField(
                blank=True,
                help_text="Summary of this page to display when this is linked from elsewhere in the site.",
            ),
        ),
    ]
