# Generated by Django 5.1.6 on 2025-07-01 21:00

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailspace", "0002_wagtailspaceindexpage_contact_subhead_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wagtailspaceindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 1), ("heading", 2), ("image", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "ol",
                                "ul",
                                "link",
                                "document",
                            ],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "h2", "h3", "link"],
                            "required": False,
                        },
                    ),
                    3: ("wagtail.images.blocks.ImageBlock", [], {}),
                },
            ),
        ),
    ]
