# Generated by Django 5.1.6 on 2025-07-03 16:28

from django.db import migrations, models
import django.db.models.deletion

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0017_drop_obsolete_alternative_text"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailspace", "0003_alter_wagtailspaceindexpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="WagtailSpacePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "social_text",
                    models.CharField(
                        blank=True,
                        help_text="Description of this page as it should appear when shared on social networks, or in Google results",
                        max_length=255,
                        verbose_name="Meta description",
                    ),
                ),
                ("heading", models.TextField(blank=True, verbose_name="Heading")),
                (
                    "sub_heading",
                    models.TextField(blank=True, verbose_name="Sub heading"),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 1), ("heading", 2), ("image", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "h2",
                                        "h3",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document",
                                    ],
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "h2", "h3", "link"],
                                    "required": False,
                                },
                            ),
                            3: ("wagtail.images.blocks.ImageBlock", [], {}),
                        },
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image to appear alongside 'Meta description', particularly for sharing on social networks",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.wagtailioimage",
                        verbose_name="Meta image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
