# Generated by Django 5.1.6 on 2025-07-03 21:07

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailspace", "0004_wagtailspacepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wagtailspaceindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 1),
                    ("heading", 3),
                    ("image", 4),
                    ("centered_heading", 6),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "ol",
                                "ul",
                                "link",
                                "document",
                            ],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "h2", "h3link"],
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 0), ("heading", 2)]],
                        {},
                    ),
                    4: ("wagtail.images.blocks.ImageBlock", [], {}),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "h2", "h3", "link"],
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 0), ("heading", 5)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="wagtailspacepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 1), ("heading", 3), ("image", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "ol",
                                "ul",
                                "link",
                                "document",
                            ],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "h2", "h3link"],
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 0), ("heading", 2)]],
                        {},
                    ),
                    4: ("wagtail.images.blocks.ImageBlock", [], {}),
                },
            ),
        ),
    ]
