# Generated by Django 5.2.5 on 2025-08-28 22:29

from django.db import migrations, models
import django.db.models.deletion

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0017_drop_obsolete_alternative_text"),
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailspace", "0004_revised_speaker_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceScheduleLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Enter the event URL from Pretalx",
                        verbose_name="Schedule URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wagtail Space Schedule URL",
                "verbose_name_plural": "Wagtail Space Schedule URLs",
            },
        ),
        migrations.CreateModel(
            name="SpaceSchedulePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "social_text",
                    models.CharField(
                        blank=True,
                        help_text="Description of this page as it should appear when shared on social networks, or in Google results",
                        max_length=255,
                        verbose_name="Meta description",
                    ),
                ),
                (
                    "listing_intro",
                    models.TextField(
                        blank=True,
                        help_text="Summary of this page to display when this is linked from elsewhere in the site.",
                    ),
                ),
                ("heading", models.TextField(blank=True, verbose_name="Heading")),
                (
                    "sub_heading",
                    models.TextField(blank=True, verbose_name="Sub heading"),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", 1),
                            ("centered_text", 1),
                            ("image", 2),
                            ("cta_button", 6),
                            ("speaker_highlight", 13),
                            ("sponsor_highlight", 19),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "h2",
                                        "h3",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document",
                                    ],
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                            2: ("wagtail.images.blocks.ImageBlock", [], {}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "CTA text",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "CTA page", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "CTA URL", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 3), ("cta_page", 4), ("cta_url", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": False},
                            ),
                            8: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Use a square image for best results."},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": True},
                            ),
                            10: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"max_length": 255, "required": False},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("speaker_image", 8),
                                        ("speaker_name", 9),
                                        ("speaker_talk", 10),
                                    ]
                                ],
                                {},
                            ),
                            12: ("wagtail.blocks.ListBlock", (11,), {}),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 7), ("speaker", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Sponsor Link", "required": True},
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("sponsor_logo", 2), ("sponsor_link", 14)]],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("sponsor_type", 9), ("sponsors", 16)]],
                                {},
                            ),
                            18: (
                                "wagtail.blocks.StreamBlock",
                                [[("sponsor", 17)]],
                                {"blank": True},
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 7), ("sponsor", 18)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image to display along with summary, when this page is linked from elsewhere in the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.wagtailioimage",
                    ),
                ),
                (
                    "schedule_url",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailspace.spaceschedulelink",
                        verbose_name="Schedule URL",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image to appear alongside 'Meta description', particularly for sharing on social networks",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.wagtailioimage",
                        verbose_name="Meta image",
                    ),
                ),
                (
                    "space_social",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailspace.spacesocialsnippet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wagtail Space Schedule Page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
