# Generated by Django 6.0.3 on 2026-05-29 19:37

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailspace", "0006_add_video_dropdown_and_extcta_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spaceschedulepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 1),
                    ("centered_text", 1),
                    ("image", 2),
                    ("cta_button", 6),
                    ("extended_cta", 9),
                    ("video", 13),
                    ("speaker_highlight", 21),
                    ("sponsor_highlight", 27),
                    ("dropdown", 32),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "ol",
                                "ul",
                                "link",
                                "document",
                            ],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "CTA text", "max_length": 255, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "CTA page", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "CTA URL", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("cta_page", 4), ("cta_url", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 255},
                    ),
                    8: ("wagtail.blocks.TextBlock", (), {"label": "Description"}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 7),
                                ("description", 8),
                                ("text", 3),
                                ("cta_page", 4),
                                ("cta_url", 5),
                            ]
                        ],
                        {},
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    11: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: ("wagtail.embeds.blocks.EmbedBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 10), ("video", 11), ("embed", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    15: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Use a square image for best results."},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link for talk description.",
                            "label": "Talk URL",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("speaker_image", 15),
                                ("speaker_name", 16),
                                ("speaker_talk", 17),
                                ("speaker_url", 18),
                            ]
                        ],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 14), ("speaker", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Sponsor Link", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("sponsor_logo", 2), ("sponsor_link", 22)]],
                        {},
                    ),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("sponsor_type", 16), ("sponsors", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [[("sponsor", 25)]],
                        {"blank": True},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 14), ("sponsor", 26)]],
                        {},
                    ),
                    28: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    29: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 28),
                                ("text", 29),
                                ("cta_text", 3),
                                ("cta_page", 4),
                                ("cta_url", 5),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 14), ("items", 31)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="wagtailspaceindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 1),
                    ("centered_text", 1),
                    ("image", 2),
                    ("cta_button", 6),
                    ("extended_cta", 9),
                    ("video", 13),
                    ("speaker_highlight", 21),
                    ("sponsor_highlight", 27),
                    ("dropdown", 32),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "ol",
                                "ul",
                                "link",
                                "document",
                            ],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "CTA text", "max_length": 255, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "CTA page", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "CTA URL", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("cta_page", 4), ("cta_url", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 255},
                    ),
                    8: ("wagtail.blocks.TextBlock", (), {"label": "Description"}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 7),
                                ("description", 8),
                                ("text", 3),
                                ("cta_page", 4),
                                ("cta_url", 5),
                            ]
                        ],
                        {},
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    11: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: ("wagtail.embeds.blocks.EmbedBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 10), ("video", 11), ("embed", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    15: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Use a square image for best results."},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link for talk description.",
                            "label": "Talk URL",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("speaker_image", 15),
                                ("speaker_name", 16),
                                ("speaker_talk", 17),
                                ("speaker_url", 18),
                            ]
                        ],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 14), ("speaker", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Sponsor Link", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("sponsor_logo", 2), ("sponsor_link", 22)]],
                        {},
                    ),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("sponsor_type", 16), ("sponsors", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [[("sponsor", 25)]],
                        {"blank": True},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 14), ("sponsor", 26)]],
                        {},
                    ),
                    28: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    29: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 28),
                                ("text", 29),
                                ("cta_text", 3),
                                ("cta_page", 4),
                                ("cta_url", 5),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 14), ("items", 31)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="wagtailspacepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 1),
                    ("centered_text", 1),
                    ("image", 2),
                    ("cta_button", 6),
                    ("extended_cta", 9),
                    ("video", 13),
                    ("speaker_highlight", 21),
                    ("sponsor_highlight", 27),
                    ("dropdown", 32),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "ol",
                                "ul",
                                "link",
                                "document",
                            ],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "CTA text", "max_length": 255, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "CTA page", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "CTA URL", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("cta_page", 4), ("cta_url", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "max_length": 255},
                    ),
                    8: ("wagtail.blocks.TextBlock", (), {"label": "Description"}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 7),
                                ("description", 8),
                                ("text", 3),
                                ("cta_page", 4),
                                ("cta_url", 5),
                            ]
                        ],
                        {},
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    11: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: ("wagtail.embeds.blocks.EmbedBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 10), ("video", 11), ("embed", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    15: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Use a square image for best results."},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link for talk description.",
                            "label": "Talk URL",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("speaker_image", 15),
                                ("speaker_name", 16),
                                ("speaker_talk", 17),
                                ("speaker_url", 18),
                            ]
                        ],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 14), ("speaker", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Sponsor Link", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("sponsor_logo", 2), ("sponsor_link", 22)]],
                        {},
                    ),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("sponsor_type", 16), ("sponsors", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [[("sponsor", 25)]],
                        {"blank": True},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 14), ("sponsor", 26)]],
                        {},
                    ),
                    28: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    29: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 28),
                                ("text", 29),
                                ("cta_text", 3),
                                ("cta_page", 4),
                                ("cta_url", 5),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 14), ("items", 31)]],
                        {},
                    ),
                },
            ),
        ),
    ]
