# Generated by Django 5.1.6 on 2025-07-04 17:34

from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailspace", "0009_spacesocial_alter_wagtailspaceindexpage_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceSocialSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("subheading", models.CharField(max_length=255)),
                (
                    "social",
                    wagtail.fields.StreamField(
                        [("social", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.URLBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageBlock", [], {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 0), ("url", 1), ("logo", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Wagtail Space Social Menu",
            },
        ),
        migrations.DeleteModel(
            name="SpaceSocial",
        ),
    ]
