# Generated by Django 5.1.6 on 2025-07-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailspace", "0013_alter_wagtailspaceindexpage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailspaceindexpage",
            name="space_social",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailspace.spacesocialsnippet",
            ),
        ),
    ]
