# Generated by Django 5.1.6 on 2025-07-07 17:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailspace', '0014_wagtailspaceindexpage_space_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagtailspacepage',
            name='space_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailspace.spacesocialsnippet'),
        ),
        migrations.AlterField(
            model_name='spacesocialsnippet',
            name='social',
            field=wagtail.fields.StreamField([('social', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.images.blocks.ImageBlock', [], {'help_text': 'Max image width of 100px for best results.'}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('url', 1), ('logo', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='spacesocialsnippet',
            name='subheading',
            field=wagtail.fields.RichTextField(max_length=255),
        ),
    ]
