# Generated by Django 5.1.6 on 2025-07-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailspace', '0015_wagtailspacepage_space_social_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wagtailspacepage',
            options={'verbose_name': 'Wagtail Space Page'},
        ),
    ]
