# Generated by Django 5.1.6 on 2025-07-16 21:18

from django.db import migrations, models
import django.db.models.deletion

import wagtail.fields


class Migration(migrations.Migration):
    replaces = [
        ("wagtailspace", "0002_wagtailspaceindexpage_listing_image_and_more"),
        ("wagtailspace", "0003_wagtailspacepage_listing_image_and_more"),
        ("wagtailspace", "0004_spacemenu"),
    ]

    dependencies = [
        ("images", "0017_drop_obsolete_alternative_text"),
        ("wagtailspace", "0001_initial_wagtailspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailspaceindexpage",
            name="listing_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to display along with summary, when this page is linked from elsewhere in the site.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.wagtailioimage",
            ),
        ),
        migrations.AddField(
            model_name="wagtailspaceindexpage",
            name="listing_intro",
            field=models.TextField(
                blank=True,
                help_text="Summary of this page to display when this is linked from elsewhere in the site.",
            ),
        ),
        migrations.AlterField(
            model_name="wagtailspaceindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 1),
                    ("centered_text", 1),
                    ("image", 2),
                    ("cta_button", 6),
                    ("speaker_highlight", 13),
                    ("sponsor_highlight", 17),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "ol",
                                "ul",
                                "link",
                                "document",
                            ],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "CTA text", "max_length": 255, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "CTA page", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "CTA URL", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("cta_page", 4), ("cta_url", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Use a square image for best results."},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    10: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("speaker_image", 8),
                                ("speaker_name", 9),
                                ("speaker_talk", 10),
                            ]
                        ],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [[("speaker", 11)]],
                        {"blank": True, "max_num": 4},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("speaker", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.ListBlock", (2,), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("sponsor_type", 9), ("sponsor_logo", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StreamBlock",
                        [[("sponsor", 15)]],
                        {"blank": True},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("sponsor", 16)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="wagtailspacepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 1),
                    ("centered_text", 1),
                    ("image", 2),
                    ("cta_button", 6),
                    ("speaker_highlight", 13),
                    ("sponsor_highlight", 17),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "ol",
                                "ul",
                                "link",
                                "document",
                            ],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "CTA text", "max_length": 255, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "CTA page", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "CTA URL", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("cta_page", 4), ("cta_url", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Use a square image for best results."},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    10: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("speaker_image", 8),
                                ("speaker_name", 9),
                                ("speaker_talk", 10),
                            ]
                        ],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [[("speaker", 11)]],
                        {"blank": True, "max_num": 4},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("speaker", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.ListBlock", (2,), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("sponsor_type", 9), ("sponsor_logo", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StreamBlock",
                        [[("sponsor", 15)]],
                        {"blank": True},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("sponsor", 16)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="wagtailspacepage",
            name="listing_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to display along with summary, when this page is linked from elsewhere in the site.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.wagtailioimage",
            ),
        ),
        migrations.AddField(
            model_name="wagtailspacepage",
            name="listing_intro",
            field=models.TextField(
                blank=True,
                help_text="Summary of this page to display when this is linked from elsewhere in the site.",
            ),
        ),
        migrations.CreateModel(
            name="SpaceMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "menu_sections",
                    wagtail.fields.StreamField(
                        [("menu_section", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "External Link", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 0),
                                        ("space_menu_page", 1),
                                        ("space_menu_url", 2),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                ("registration_url", models.URLField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Wagtail Space menu",
            },
        ),
    ]
