# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models


def update_icons(apps, schema_editor):
    DevelopersPageOptions = apps.get_model("developers", "DevelopersPageOptions")

    DevelopersPageOptions.objects.filter(icon="fa-github").update(icon="github")
    DevelopersPageOptions.objects.filter(icon="fa-eye").update(icon="documentation")
    DevelopersPageOptions.objects.filter(icon="fa-google").update(icon="social")

    # We have no entries in the database with this icon, but let's cover this case
    DevelopersPageOptions.objects.filter(icon="fa-server").update(icon="social")


def reverse_update_icons(apps, schema_editor):
    DevelopersPageOptions = apps.get_model("developers", "DevelopersPageOptions")

    DevelopersPageOptions.objects.filter(icon="github").update(icon="fa-github")
    DevelopersPageOptions.objects.filter(icon="documentation").update(icon="fa-eye")
    DevelopersPageOptions.objects.filter(icon="social").update(icon="fa-google")


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0002_auto_20160728_1321"),
    ]

    operations = [
        migrations.RunPython(update_icons, reverse_update_icons),
        migrations.AlterField(
            model_name="developerspageoptions",
            name="icon",
            field=models.CharField(
                choices=[
                    ("github", "Github"),
                    ("social", "Social"),
                    ("documentation", "Documentation"),
                ],
                max_length=255,
            ),
        ),
    ]
