# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-01 12:15
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_developerspageoptions_icon_new_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerspage',
            name='body_heading',
        ),
        migrations.RemoveField(
            model_name='developerspage',
            name='introduction',
        ),
        migrations.AlterField(
            model_name='developerspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('code', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('subtitle', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('django', 'Django templating language'), ('html', 'HTML'), ('javascript', 'Javascript'), ('python', 'Python'), ('scss', 'SCSS')])), ('code', wagtail.wagtailcore.blocks.TextBlock())))), ('link', wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock()), ('link_text_bold', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('link_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.wagtailcore.blocks.CharBlock(required=False)))))), template='developers/blocks/code_with_link_block.html')),)),
        ),
    ]
