# Generated by Django 3.2.16 on 2022-10-04 12:34

from django.db import migrations

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0005_auto_20190813_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developerspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "code",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("subtitle", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "code",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "language",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("bash", "Bash/Shell"),
                                                        ("css", "CSS"),
                                                        (
                                                            "django",
                                                            "Django templating language",
                                                        ),
                                                        ("html", "HTML"),
                                                        ("javascript", "Javascript"),
                                                        ("python", "Python"),
                                                        ("scss", "SCSS"),
                                                    ]
                                                ),
                                            ),
                                            ("code", wagtail.blocks.TextBlock()),
                                        ]
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("link_text", wagtail.blocks.CharBlock()),
                                            (
                                                "link_text_bold",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "link_page",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "link_url",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ],
                            template="developers/blocks/code_with_link_block.html",
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
