image:
  file: .gitpod.Dockerfile
tasks:
  - before: |
      curl https://cli-assets.heroku.com/install.sh | sh
      pip install fabric
    init: fab build
    command: |
      fab start
      fab migrate
ports:
  - port: 8000
vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker
