# Generated by Django 1.9.8 on 2016-07-28 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="newsletteremailaddress",
            table=None,
        ),
        migrations.AlterModelTable(
            name="newsletterindexpage",
            table=None,
        ),
        migrations.AlterModelTable(
            name="newsletterpage",
            table=None,
        ),
    ]
