# Generated by Django 5.1.6 on 2025-02-25 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_newsletteremailaddress_signed_up_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletterpage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="newsletterpage",
            name="intro",
        ),
    ]
