# Generated by Django 5.1.6 on 2025-04-16 13:02

from django.db import migrations, models
import django.db.models.deletion

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_newsletteremailaddress_signed_up_at"),
        ("wagtail_newsletter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "footer",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("rich_text", 1),
                            ("accent_rich_text", 2),
                            ("image", 3),
                            ("button", 7),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtailio.newsletter.blocks.HeadingBlock", (), {}),
                            1: (
                                "wagtailio.newsletter.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                    ]
                                },
                            ),
                            2: (
                                "wagtailio.newsletter.blocks.AccentRichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                    ]
                                },
                            ),
                            3: ("wagtailio.newsletter.blocks.ImageBlock", (), {}),
                            4: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            5: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "External URL to link to",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Internal page to link to",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 4), ("url", 5), ("page", 6)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="preview",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("rich_text", 1),
                    ("accent_rich_text", 2),
                    ("image", 3),
                    ("button", 7),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtailio.newsletter.blocks.HeadingBlock", (), {}),
                    1: (
                        "wagtailio.newsletter.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                            ]
                        },
                    ),
                    2: (
                        "wagtailio.newsletter.blocks.AccentRichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                            ]
                        },
                    ),
                    3: ("wagtailio.newsletter.blocks.ImageBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External URL to link to", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Internal page to link to", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 4), ("url", 5), ("page", 6)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="newsletter_campaign",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="newsletter_recipients",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtail_newsletter.newsletterrecipients",
            ),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="newsletter_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject for the newsletter. Defaults to page title if blank.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="date",
            field=models.DateField(),
        ),
    ]
