# Generated by Django 5.1.6 on 2025-04-16 13:02

from django.db import migrations, models
import django.db.models.deletion

import wagtail.fields


def convert_body_to_streamfield(apps, schema_editor):
    from bs4 import BeautifulSoup

    NewsletterPage = apps.get_model("newsletter", "NewsletterPage")
    for page in NewsletterPage.objects.all():
        soup = BeautifulSoup(page.intro, "html.parser")
        preview = soup.get_text(strip=True)
        if preview:
            page.preview = preview
            page.save()

        if page.body:
            page.content = [{"type": "rich_text", "value": page.body}]
            page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_newsletteremailaddress_signed_up_at"),
        ("wagtail_newsletter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "footer",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("rich_text", 1),
                            ("accent_rich_text", 2),
                            ("image", 3),
                            ("button", 6),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtailio.newsletter.blocks.HeadingBlock", (), {}),
                            1: (
                                "wagtailio.newsletter.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                    ]
                                },
                            ),
                            2: (
                                "wagtailio.newsletter.blocks.AccentRichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                    ]
                                },
                            ),
                            3: ("wagtailio.newsletter.blocks.ImageBlock", (), {}),
                            4: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            5: ("wagtail.blocks.URLBlock", (), {"required": True}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 4), ("url", 5)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="preview",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("rich_text", 1),
                    ("accent_rich_text", 2),
                    ("image", 3),
                    ("button", 6),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtailio.newsletter.blocks.HeadingBlock", (), {}),
                    1: (
                        "wagtailio.newsletter.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                            ]
                        },
                    ),
                    2: (
                        "wagtailio.newsletter.blocks.AccentRichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                            ]
                        },
                    ),
                    3: ("wagtailio.newsletter.blocks.ImageBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    5: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    6: ("wagtail.blocks.StructBlock", [[("text", 4), ("url", 5)]], {}),
                },
            ),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="newsletter_campaign",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="newsletter_recipients",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtail_newsletter.newsletterrecipients",
            ),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="newsletter_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject for the newsletter. Defaults to page title if blank.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="date",
            field=models.DateField(),
        ),
        migrations.RunPython(convert_body_to_streamfield, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="newsletterpage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="newsletterpage",
            name="intro",
        ),
        migrations.RenameField(
            model_name="newsletterpage",
            old_name="content",
            new_name="body",
        ),
    ]
