# Generated by Django 3.2.18 on 2023-12-15 21:36

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletteremailaddress_signed_up_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterpage',
            name='mailchimp_campaign_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='mailchimp_campaign_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newsletterpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
