# Generated by Django 5.1.6 on 2025-04-16 13:02

import re

from django.db import migrations


def convert_body_to_streamfield(apps, schema_editor):
    from bs4 import BeautifulSoup

    NewsletterPage = apps.get_model("newsletter", "NewsletterPage")
    for page in NewsletterPage.objects.all():
        soup = BeautifulSoup(page.intro, "html.parser")
        preview = soup.get_text(strip=True)
        if preview:
            page.preview = preview
            page.save()

        if page.body:
            # Split content on image embeds
            pattern = r'(<embed[^>]*embedtype="image"[^>]*id="(?:\d+)"[^>]*>)'
            parts = re.split(pattern, page.body)

            content_blocks = []

            for part in parts:
                if part.startswith("<embed") and part.endswith(">"):
                    # This is an image embed
                    image_id = re.search(r'id="(\d+)"', part)
                    if image_id:
                        content_blocks.append(
                            {"type": "image", "value": int(image_id.group(1))}
                        )
                else:
                    content_blocks.append({"type": "rich_text", "value": part})

            page.content = content_blocks
            page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0004_wagtail_newsletter_model"),
    ]

    operations = [
        migrations.RunPython(convert_body_to_streamfield, migrations.RunPython.noop),
    ]
