# Generated by Django 5.1.6 on 2025-02-25 13:35

from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0004_remove_newsletterpage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletterpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 2),
                    ("content", 4),
                    ("image", 8),
                    ("call_to_action", 11),
                    ("package_list", 15),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The heading text", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h1", "H1"), ("h2", "H2")]},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("size", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    4: ("wagtail.blocks.StructBlock", [[("text", 3)]], {}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Provide descriptive alt text for the image",
                            "required": True,
                        },
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 5), ("alt_text", 6), ("caption", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    10: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 9), ("url", 10), ("button_text", 9)]],
                        {},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"default": "Packages"}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 9), ("version", 9), ("url", 10)]],
                        {},
                    ),
                    14: ("wagtail.blocks.ListBlock", (13,), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("packages", 14)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="issue_number",
            field=models.IntegerField(
                default=0, help_text="The issue number of the newsletter"
            ),
        ),
        migrations.AddField(
            model_name="newsletterpage",
            name="preview_text",
            field=models.CharField(
                blank=True,
                help_text="A short preview of the newsletter content that appears in email clients",
                max_length=300,
            ),
        ),
    ]
