# Generated by Django 5.1.6 on 2025-04-16 13:02

from django.db import migrations


def convert_body_to_streamfield(apps, schema_editor):
    from bs4 import BeautifulSoup

    NewsletterPage = apps.get_model("newsletter", "NewsletterPage")
    for page in NewsletterPage.objects.all():
        soup = BeautifulSoup(page.intro, "html.parser")
        preview = soup.get_text(strip=True)
        if preview:
            page.preview = preview
            page.save()

        if page.body:
            page.content = [{"type": "rich_text", "value": page.body}]
            page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0004_wagtail_newsletter_model"),
    ]

    operations = [
        migrations.RunPython(convert_body_to_streamfield, migrations.RunPython.noop),
    ]
