# Generated by Django 5.1.6 on 2025-02-25 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0004_install_wagtail_newsletter"),
        (
            "newsletter",
            "0005_newsletterpage_content_newsletterpage_issue_number_and_more",
        ),
    ]

    operations = []
