# Generated by Django 5.1.6 on 2025-05-01 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0005_wagtail_newsletter_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletterpage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="newsletterpage",
            name="intro",
        ),
        migrations.RenameField(
            model_name="newsletterpage",
            old_name="content",
            new_name="body",
        ),
    ]
