# Generated by Django 2.2.13 on 2020-12-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standardpage', '0004_auto_20190813_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('standardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='standardpage.StandardPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('standardpage.standardpage',),
        ),
    ]
