# Generated by Django 2.2.13 on 2020-12-04 06:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_create_calltoactionsnippet'),
        ('service', '0001_create_servicepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utils.CallToActionSnippet'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='strapline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ServicePageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=100)),
                ('icon_name', models.CharField(choices=[('tooling', 'Tooling'), ('architecture', 'Architecture'), ('review', 'Review'), ('api', 'API'), ('develop', 'Develop'), ('migration', 'Migration'), ('more', 'More')], max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service.ServicePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
