# Generated by Django 3.2.12 on 2022-09-28 15:17

import django.db.models.deletion
from django.db import migrations, models

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("core", "0046_update_svg_icon_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterMenu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sections",
                    wagtail.fields.StreamField(
                        [
                            (
                                "section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(max_length=255),
                                        ),
                                        (
                                            "links",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "text",
                                                            wagtail.blocks.CharBlock(
                                                                max_length=100
                                                            ),
                                                        ),
                                                        (
                                                            "cta_page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                label="Page",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "cta_url",
                                                            wagtail.blocks.URLBlock(
                                                                label="URL",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer menu",
            },
        ),
        migrations.CreateModel(
            name="MainMenu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "menu_sections",
                    wagtail.fields.StreamField(
                        [
                            (
                                "menu_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "name",
                                            wagtail.blocks.CharBlock(max_length=255),
                                        ),
                                        (
                                            "nav_items",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "text",
                                                            wagtail.blocks.CharBlock(
                                                                label="Nav item name",
                                                                max_length=55,
                                                            ),
                                                        ),
                                                        (
                                                            "short_description",
                                                            wagtail.blocks.CharBlock(
                                                                max_length=55,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "icon",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "arrow-alt",
                                                                        "Arrow alt",
                                                                    ),
                                                                    (
                                                                        "arrow-in-circle",
                                                                        "Arrow in circle",
                                                                    ),
                                                                    (
                                                                        "arrow-in-square",
                                                                        "Arrow in square",
                                                                    ),
                                                                    (
                                                                        "arrows",
                                                                        "Arrows",
                                                                    ),
                                                                    ("blog", "Blog"),
                                                                    ("bread", "Bread"),
                                                                    (
                                                                        "briefcase",
                                                                        "Briefcase",
                                                                    ),
                                                                    (
                                                                        "building",
                                                                        "Building",
                                                                    ),
                                                                    (
                                                                        "calendar",
                                                                        "Calendar",
                                                                    ),
                                                                    (
                                                                        "code-file",
                                                                        "Code File",
                                                                    ),
                                                                    (
                                                                        "document",
                                                                        "Document",
                                                                    ),
                                                                    (
                                                                        "envelope",
                                                                        "Envelope",
                                                                    ),
                                                                    (
                                                                        "explanation",
                                                                        "Explanation",
                                                                    ),
                                                                    ("eye", "Eye"),
                                                                    ("flame", "Flame"),
                                                                    (
                                                                        "friends",
                                                                        "Friends",
                                                                    ),
                                                                    (
                                                                        "github",
                                                                        "Github",
                                                                    ),
                                                                    (
                                                                        "handshake",
                                                                        "Handshake",
                                                                    ),
                                                                    ("heart", "Heart"),
                                                                    (
                                                                        "history",
                                                                        "History",
                                                                    ),
                                                                    (
                                                                        "id-card",
                                                                        "ID Card",
                                                                    ),
                                                                    ("image", "Image"),
                                                                    (
                                                                        "knife-fork",
                                                                        "Knife Fork",
                                                                    ),
                                                                    ("leaf", "Leaf"),
                                                                    (
                                                                        "location-pin",
                                                                        "Location Pin",
                                                                    ),
                                                                    ("map", "Map"),
                                                                    (
                                                                        "magnifying-glass",
                                                                        "Magnifying Glass",
                                                                    ),
                                                                    ("money", "Money"),
                                                                    ("moon", "Moon"),
                                                                    (
                                                                        "one-two-steps",
                                                                        "One Two Steps",
                                                                    ),
                                                                    (
                                                                        "padlock",
                                                                        "Padlock",
                                                                    ),
                                                                    (
                                                                        "paper-plane",
                                                                        "Paper Plane",
                                                                    ),
                                                                    (
                                                                        "paper-stack",
                                                                        "Paper Stack",
                                                                    ),
                                                                    (
                                                                        "pen-checkbox",
                                                                        "Pen Checkbox",
                                                                    ),
                                                                    (
                                                                        "person-in-tie",
                                                                        "Person in Tie",
                                                                    ),
                                                                    (
                                                                        "python",
                                                                        "Python",
                                                                    ),
                                                                    (
                                                                        "question-mark-circle",
                                                                        "Question Mark Circle",
                                                                    ),
                                                                    (
                                                                        "quotes",
                                                                        "Quotes",
                                                                    ),
                                                                    (
                                                                        "release-cycle",
                                                                        "Release Cycle",
                                                                    ),
                                                                    (
                                                                        "roadmap",
                                                                        "Roadmap",
                                                                    ),
                                                                    (
                                                                        "rocket",
                                                                        "Rocket",
                                                                    ),
                                                                    (
                                                                        "rollback",
                                                                        "Rollback",
                                                                    ),
                                                                    ("slack", "Slack"),
                                                                    (
                                                                        "speech-bubble",
                                                                        "Speech Bubble",
                                                                    ),
                                                                    (
                                                                        "sun-cloud",
                                                                        "Sun Cloud",
                                                                    ),
                                                                    (
                                                                        "table-tennis",
                                                                        "Table Tennis",
                                                                    ),
                                                                    ("tree", "Tree"),
                                                                    (
                                                                        "wordpress",
                                                                        "Wordpress",
                                                                    ),
                                                                    ("world", "World"),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "cta_page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                label="Page",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "cta_url",
                                                            wagtail.blocks.URLBlock(
                                                                label="External Link",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                        (
                                            "call_to_action",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "text",
                                                        wagtail.blocks.CharBlock(
                                                            label="Heading",
                                                            max_length=255,
                                                        ),
                                                    ),
                                                    (
                                                        "sub_heading",
                                                        wagtail.blocks.CharBlock(
                                                            max_length=255,
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "description",
                                                        wagtail.blocks.CharBlock(
                                                            max_length=255,
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "icon",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                (
                                                                    "arrow-alt",
                                                                    "Arrow alt",
                                                                ),
                                                                (
                                                                    "arrow-in-circle",
                                                                    "Arrow in circle",
                                                                ),
                                                                (
                                                                    "arrow-in-square",
                                                                    "Arrow in square",
                                                                ),
                                                                ("arrows", "Arrows"),
                                                                ("blog", "Blog"),
                                                                ("bread", "Bread"),
                                                                (
                                                                    "briefcase",
                                                                    "Briefcase",
                                                                ),
                                                                (
                                                                    "building",
                                                                    "Building",
                                                                ),
                                                                (
                                                                    "calendar",
                                                                    "Calendar",
                                                                ),
                                                                (
                                                                    "code-file",
                                                                    "Code File",
                                                                ),
                                                                (
                                                                    "document",
                                                                    "Document",
                                                                ),
                                                                (
                                                                    "envelope",
                                                                    "Envelope",
                                                                ),
                                                                (
                                                                    "explanation",
                                                                    "Explanation",
                                                                ),
                                                                ("eye", "Eye"),
                                                                ("flame", "Flame"),
                                                                ("friends", "Friends"),
                                                                ("github", "Github"),
                                                                (
                                                                    "handshake",
                                                                    "Handshake",
                                                                ),
                                                                ("heart", "Heart"),
                                                                ("history", "History"),
                                                                ("id-card", "ID Card"),
                                                                ("image", "Image"),
                                                                (
                                                                    "knife-fork",
                                                                    "Knife Fork",
                                                                ),
                                                                ("leaf", "Leaf"),
                                                                (
                                                                    "location-pin",
                                                                    "Location Pin",
                                                                ),
                                                                ("map", "Map"),
                                                                (
                                                                    "magnifying-glass",
                                                                    "Magnifying Glass",
                                                                ),
                                                                ("money", "Money"),
                                                                ("moon", "Moon"),
                                                                (
                                                                    "one-two-steps",
                                                                    "One Two Steps",
                                                                ),
                                                                ("padlock", "Padlock"),
                                                                (
                                                                    "paper-plane",
                                                                    "Paper Plane",
                                                                ),
                                                                (
                                                                    "paper-stack",
                                                                    "Paper Stack",
                                                                ),
                                                                (
                                                                    "pen-checkbox",
                                                                    "Pen Checkbox",
                                                                ),
                                                                (
                                                                    "person-in-tie",
                                                                    "Person in Tie",
                                                                ),
                                                                ("python", "Python"),
                                                                (
                                                                    "question-mark-circle",
                                                                    "Question Mark Circle",
                                                                ),
                                                                ("quotes", "Quotes"),
                                                                (
                                                                    "release-cycle",
                                                                    "Release Cycle",
                                                                ),
                                                                ("roadmap", "Roadmap"),
                                                                ("rocket", "Rocket"),
                                                                (
                                                                    "rollback",
                                                                    "Rollback",
                                                                ),
                                                                ("slack", "Slack"),
                                                                (
                                                                    "speech-bubble",
                                                                    "Speech Bubble",
                                                                ),
                                                                (
                                                                    "sun-cloud",
                                                                    "Sun Cloud",
                                                                ),
                                                                (
                                                                    "table-tennis",
                                                                    "Table Tennis",
                                                                ),
                                                                ("tree", "Tree"),
                                                                (
                                                                    "wordpress",
                                                                    "Wordpress",
                                                                ),
                                                                ("world", "World"),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "cta_page",
                                                        wagtail.blocks.PageChooserBlock(
                                                            label="Page", required=False
                                                        ),
                                                    ),
                                                    (
                                                        "cta_url",
                                                        wagtail.blocks.URLBlock(
                                                            label="External Link",
                                                            required=False,
                                                        ),
                                                    ),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Main menu",
            },
        ),
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "footer_navigation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="navigation.footermenu",
                    ),
                ),
                (
                    "get_started_menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.getstartedsnippet",
                    ),
                ),
                (
                    "main_navigation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="navigation.mainmenu",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
