# Generated by Django 3.2.16 on 2022-10-04 12:34

from django.db import migrations

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footermenu",
            name="sections",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "text",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=100
                                                    ),
                                                ),
                                                (
                                                    "cta_page",
                                                    wagtail.blocks.PageChooserBlock(
                                                        label="Page", required=False
                                                    ),
                                                ),
                                                (
                                                    "cta_url",
                                                    wagtail.blocks.URLBlock(
                                                        label="URL", required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="mainmenu",
            name="menu_sections",
            field=wagtail.fields.StreamField(
                [
                    (
                        "menu_section",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    "nav_items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "text",
                                                    wagtail.blocks.CharBlock(
                                                        label="Nav item name",
                                                        max_length=55,
                                                    ),
                                                ),
                                                (
                                                    "short_description",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=55, required=False
                                                    ),
                                                ),
                                                (
                                                    "icon",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("arrow-alt", "Arrow alt"),
                                                            (
                                                                "arrow-in-circle",
                                                                "Arrow in circle",
                                                            ),
                                                            (
                                                                "arrow-in-square",
                                                                "Arrow in square",
                                                            ),
                                                            ("arrows", "Arrows"),
                                                            ("blog", "Blog"),
                                                            ("bread", "Bread"),
                                                            ("briefcase", "Briefcase"),
                                                            ("building", "Building"),
                                                            ("calendar", "Calendar"),
                                                            ("code-file", "Code File"),
                                                            ("document", "Document"),
                                                            ("envelope", "Envelope"),
                                                            (
                                                                "explanation",
                                                                "Explanation",
                                                            ),
                                                            ("eye", "Eye"),
                                                            ("flame", "Flame"),
                                                            ("friends", "Friends"),
                                                            ("github", "Github"),
                                                            ("handshake", "Handshake"),
                                                            ("heart", "Heart"),
                                                            ("history", "History"),
                                                            ("id-card", "ID Card"),
                                                            ("image", "Image"),
                                                            (
                                                                "knife-fork",
                                                                "Knife Fork",
                                                            ),
                                                            ("leaf", "Leaf"),
                                                            (
                                                                "location-pin",
                                                                "Location Pin",
                                                            ),
                                                            ("map", "Map"),
                                                            (
                                                                "magnifying-glass",
                                                                "Magnifying Glass",
                                                            ),
                                                            ("money", "Money"),
                                                            ("moon", "Moon"),
                                                            (
                                                                "one-two-steps",
                                                                "One Two Steps",
                                                            ),
                                                            ("padlock", "Padlock"),
                                                            (
                                                                "paper-plane",
                                                                "Paper Plane",
                                                            ),
                                                            (
                                                                "paper-stack",
                                                                "Paper Stack",
                                                            ),
                                                            (
                                                                "pen-checkbox",
                                                                "Pen Checkbox",
                                                            ),
                                                            (
                                                                "person-in-tie",
                                                                "Person in Tie",
                                                            ),
                                                            ("python", "Python"),
                                                            (
                                                                "question-mark-circle",
                                                                "Question Mark Circle",
                                                            ),
                                                            ("quotes", "Quotes"),
                                                            (
                                                                "release-cycle",
                                                                "Release Cycle",
                                                            ),
                                                            ("roadmap", "Roadmap"),
                                                            ("rocket", "Rocket"),
                                                            ("rollback", "Rollback"),
                                                            ("slack", "Slack"),
                                                            (
                                                                "speech-bubble",
                                                                "Speech Bubble",
                                                            ),
                                                            ("sun-cloud", "Sun Cloud"),
                                                            (
                                                                "table-tennis",
                                                                "Table Tennis",
                                                            ),
                                                            ("tree", "Tree"),
                                                            ("wordpress", "Wordpress"),
                                                            ("world", "World"),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "cta_page",
                                                    wagtail.blocks.PageChooserBlock(
                                                        label="Page", required=False
                                                    ),
                                                ),
                                                (
                                                    "cta_url",
                                                    wagtail.blocks.URLBlock(
                                                        label="External Link",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "call_to_action",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Heading", max_length=255
                                                ),
                                            ),
                                            (
                                                "sub_heading",
                                                wagtail.blocks.CharBlock(
                                                    max_length=255, required=False
                                                ),
                                            ),
                                            (
                                                "description",
                                                wagtail.blocks.CharBlock(
                                                    max_length=255, required=False
                                                ),
                                            ),
                                            (
                                                "icon",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("arrow-alt", "Arrow alt"),
                                                        (
                                                            "arrow-in-circle",
                                                            "Arrow in circle",
                                                        ),
                                                        (
                                                            "arrow-in-square",
                                                            "Arrow in square",
                                                        ),
                                                        ("arrows", "Arrows"),
                                                        ("blog", "Blog"),
                                                        ("bread", "Bread"),
                                                        ("briefcase", "Briefcase"),
                                                        ("building", "Building"),
                                                        ("calendar", "Calendar"),
                                                        ("code-file", "Code File"),
                                                        ("document", "Document"),
                                                        ("envelope", "Envelope"),
                                                        ("explanation", "Explanation"),
                                                        ("eye", "Eye"),
                                                        ("flame", "Flame"),
                                                        ("friends", "Friends"),
                                                        ("github", "Github"),
                                                        ("handshake", "Handshake"),
                                                        ("heart", "Heart"),
                                                        ("history", "History"),
                                                        ("id-card", "ID Card"),
                                                        ("image", "Image"),
                                                        ("knife-fork", "Knife Fork"),
                                                        ("leaf", "Leaf"),
                                                        (
                                                            "location-pin",
                                                            "Location Pin",
                                                        ),
                                                        ("map", "Map"),
                                                        (
                                                            "magnifying-glass",
                                                            "Magnifying Glass",
                                                        ),
                                                        ("money", "Money"),
                                                        ("moon", "Moon"),
                                                        (
                                                            "one-two-steps",
                                                            "One Two Steps",
                                                        ),
                                                        ("padlock", "Padlock"),
                                                        ("paper-plane", "Paper Plane"),
                                                        ("paper-stack", "Paper Stack"),
                                                        (
                                                            "pen-checkbox",
                                                            "Pen Checkbox",
                                                        ),
                                                        (
                                                            "person-in-tie",
                                                            "Person in Tie",
                                                        ),
                                                        ("python", "Python"),
                                                        (
                                                            "question-mark-circle",
                                                            "Question Mark Circle",
                                                        ),
                                                        ("quotes", "Quotes"),
                                                        (
                                                            "release-cycle",
                                                            "Release Cycle",
                                                        ),
                                                        ("roadmap", "Roadmap"),
                                                        ("rocket", "Rocket"),
                                                        ("rollback", "Rollback"),
                                                        ("slack", "Slack"),
                                                        (
                                                            "speech-bubble",
                                                            "Speech Bubble",
                                                        ),
                                                        ("sun-cloud", "Sun Cloud"),
                                                        (
                                                            "table-tennis",
                                                            "Table Tennis",
                                                        ),
                                                        ("tree", "Tree"),
                                                        ("wordpress", "Wordpress"),
                                                        ("world", "World"),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "cta_page",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Page", required=False
                                                ),
                                            ),
                                            (
                                                "cta_url",
                                                wagtail.blocks.URLBlock(
                                                    label="External Link",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
