# Generated by Django 5.1.6 on 2025-07-16 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0002_streamfield_use_json_field"),
        ("wagtailspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationsettings",
            name="space_navigation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailspace.spacemenu",
            ),
        ),
    ]
