# Generated by Django 5.1.6 on 2025-07-15 22:47

from django.db import migrations, models
import django.db.models.deletion

import wagtail.fields


class Migration(migrations.Migration):
    replaces = [
        ("navigation", "0003_spacemenu_navigationsettings_space_navigation"),
        ("navigation", "0004_alter_spacemenu_menu_sections"),
        ("navigation", "0005_spacemenu_registration_url"),
        ("navigation", "0006_alter_spacemenu_registration_url"),
    ]

    dependencies = [
        ("navigation", "0002_streamfield_use_json_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceMenu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "menu_sections",
                    wagtail.fields.StreamField(
                        [("menu_section", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "External Link", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 0),
                                        ("space_menu_page", 1),
                                        ("space_menu_url", 2),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                ("registration_url", models.URLField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Wagtail Space menu",
            },
        ),
        migrations.AddField(
            model_name="navigationsettings",
            name="space_navigation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="navigation.spacemenu",
            ),
        ),
    ]
