# Generated by Django 5.1.6 on 2025-07-01 16:10

from django.db import migrations, models
import django.db.models.deletion

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0002_streamfield_use_json_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceMenu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "menu_sections",
                    wagtail.fields.StreamField(
                        [("menu_section", 11)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Nav item name", "max_length": 55},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 55, "required": False},
                            ),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("arrow-alt", "Arrow alt"),
                                        ("arrow-in-circle", "Arrow in circle"),
                                        ("arrow-in-square", "Arrow in square"),
                                        ("arrows", "Arrows"),
                                        ("blog", "Blog"),
                                        ("bread", "Bread"),
                                        ("briefcase", "Briefcase"),
                                        ("building", "Building"),
                                        ("calendar", "Calendar"),
                                        ("code-file", "Code File"),
                                        ("document", "Document"),
                                        ("envelope", "Envelope"),
                                        ("explanation", "Explanation"),
                                        ("eye", "Eye"),
                                        ("flame", "Flame"),
                                        ("friends", "Friends"),
                                        ("github", "Github"),
                                        ("handshake", "Handshake"),
                                        ("heart", "Heart"),
                                        ("history", "History"),
                                        ("id-card", "ID Card"),
                                        ("image", "Image"),
                                        ("knife-fork", "Knife Fork"),
                                        ("leaf", "Leaf"),
                                        ("location-pin", "Location Pin"),
                                        ("map", "Map"),
                                        ("magnifying-glass", "Magnifying Glass"),
                                        ("money", "Money"),
                                        ("moon", "Moon"),
                                        ("one-two-steps", "One Two Steps"),
                                        ("padlock", "Padlock"),
                                        ("paper-plane", "Paper Plane"),
                                        ("paper-stack", "Paper Stack"),
                                        ("pen-checkbox", "Pen Checkbox"),
                                        ("person-in-tie", "Person in Tie"),
                                        ("python", "Python"),
                                        (
                                            "question-mark-circle",
                                            "Question Mark Circle",
                                        ),
                                        ("quotes", "Quotes"),
                                        ("release-cycle", "Release Cycle"),
                                        ("roadmap", "Roadmap"),
                                        ("rocket", "Rocket"),
                                        ("rollback", "Rollback"),
                                        ("slack", "Slack"),
                                        ("speech-bubble", "Speech Bubble"),
                                        ("sun-cloud", "Sun Cloud"),
                                        ("table-tennis", "Table Tennis"),
                                        ("tree", "Tree"),
                                        ("wordpress", "Wordpress"),
                                        ("world", "World"),
                                    ]
                                },
                            ),
                            4: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "External Link", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 1),
                                        ("short_description", 2),
                                        ("icon", 3),
                                        ("cta_page", 4),
                                        ("cta_url", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: ("wagtail.blocks.ListBlock", (6,), {}),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Heading", "max_length": 255},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": False},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 8),
                                        ("sub_heading", 9),
                                        ("description", 9),
                                        ("icon", 3),
                                        ("cta_page", 4),
                                        ("cta_url", 5),
                                    ]
                                ],
                                {"required": False},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 0),
                                        ("nav_items", 7),
                                        ("call_to_action", 10),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Wagtail Space menu",
            },
        ),
        migrations.AddField(
            model_name="navigationsettings",
            name="space_navigation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="navigation.spacemenu",
            ),
        ),
    ]
