# Generated by Django 5.1.6 on 2025-07-01 19:38

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0003_spacemenu_navigationsettings_space_navigation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spacemenu",
            name="menu_sections",
            field=wagtail.fields.StreamField(
                [("menu_section", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External Link", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("space_menu_page", 1), ("space_menu_url", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
