# Generated by Django 5.1.6 on 2025-07-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0004_alter_spacemenu_menu_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacemenu",
            name="registration_url",
            field=models.URLField(null=True),
        ),
    ]
