# Generated by Django 5.1.6 on 2025-07-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0005_spacemenu_registration_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spacemenu",
            name="registration_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
