# Generated by Django 3.2.8 on 2022-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areweheadlessyet", "0002_areweheadlessyethomepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areweheadlessyethomepage",
            name="strapline_icon",
            field=models.CharField(
                choices=[("thumbs up", "thumbs up"), ("thumbs down", "thumbs down")],
                default="thumbs up",
                max_length=15,
            ),
        ),
    ]
