# Generated by Django 1.9.8 on 2016-07-28 13:15

from django.db import migrations


def forwards_func(apps, schema_editor):
    ContentType = apps.get_model("contenttypes.ContentType")

    ContentType.objects.filter(app_label="developers", model="developerspage").delete()
    ContentType.objects.filter(app_label="core", model="developerspage").update(
        app_label="developers", model="developerspage"
    )

    ContentType.objects.filter(
        app_label="developers", model="developerspageoptions"
    ).delete()
    ContentType.objects.filter(app_label="core", model="developerspageoptions").update(
        app_label="developers", model="developerspageoptions"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailredirects", "0005_capitalizeverbose"),
        ("wagtailcore", "0028_merge"),
        ("wagtailforms", "0003_capitalizeverbose"),
        ("core", "0030_auto_20160728_1040"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="developerspage",
                    name="listing_image",
                ),
                migrations.RemoveField(
                    model_name="developerspage",
                    name="page_ptr",
                ),
                migrations.RemoveField(
                    model_name="developerspage",
                    name="social_image",
                ),
                migrations.RemoveField(
                    model_name="developerspageoptions",
                    name="internal_link",
                ),
                migrations.RemoveField(
                    model_name="developerspageoptions",
                    name="page",
                ),
                migrations.DeleteModel(
                    name="DevelopersPage",
                ),
                migrations.DeleteModel(
                    name="DevelopersPageOptions",
                ),
            ],
            database_operations=[],
        ),
    ]
