# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 10:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('core', '0033_auto_20160729_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagenew',
            name='listing_image',
        ),
        migrations.RemoveField(
            model_name='homepagenew',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepagenew',
            name='social_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('banner', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(max_length=128)), ('sub_title', wagtail.wagtailcore.blocks.CharBlock(max_length=128)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock()), ('link_text_bold', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('link_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.wagtailcore.blocks.CharBlock(required=False))))))))),), default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HomePageNew',
        ),
    ]
