# Generated by Django 3.2.12 on 2022-08-02 17:06

import django.db.models.deletion
from django.db import migrations, models

import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("core", "0040_bannerblock_video"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="LinkGroupSnippet",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "name",
                            models.CharField(
                                help_text="The name of the menu for internal identification e.g 'Primary', 'Footer'.",
                                max_length=255,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Link group",
                        "ordering": ["name"],
                    },
                ),
            ],
            # Table already exists. See See wagtailio/utils/migrations/0002_auto_20220802_1706.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="MenuSnippet",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "menu_name",
                            models.CharField(
                                help_text="The name of the menu for internal identification e.g 'Primary', 'Footer'.",
                                max_length=255,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Menu",
                        "ordering": ["menu_name"],
                    },
                ),
            ],
            # Table already exists. See See wagtailio/utils/migrations/0002_auto_20220802_1706.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="MenuSnippetLink",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "sort_order",
                            models.IntegerField(blank=True, editable=False, null=True),
                        ),
                        (
                            "link_text",
                            models.TextField(
                                blank=True,
                                help_text="Optional. Override title text for chosen link page",
                            ),
                        ),
                        (
                            "link_page",
                            models.ForeignKey(
                                blank=True,
                                help_text="Choose a page to which to link",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                to="wagtailcore.page",
                            ),
                        ),
                        (
                            "snippet",
                            modelcluster.fields.ParentalKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="links",
                                to="core.menusnippet",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["sort_order"],
                        "abstract": False,
                    },
                ),
            ],
            # Table already exists. See See wagtailio/utils/migrations/0002_auto_20220802_1706.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="LinkGroupLink",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "sort_order",
                            models.IntegerField(blank=True, editable=False, null=True),
                        ),
                        (
                            "link_URL",
                            models.URLField(help_text="Choose a URL to which to link"),
                        ),
                        ("link_text", models.TextField(help_text="Text of the link")),
                        (
                            "link_description",
                            models.TextField(blank=True, help_text="Optional"),
                        ),
                        (
                            "link_icon",
                            models.TextField(
                                blank=True,
                                help_text="Optional. The code of a Fontawesome icon to display beside this link e.g fa-twitter",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "snippet",
                            modelcluster.fields.ParentalKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="links",
                                to="core.linkgroupsnippet",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["sort_order"],
                        "abstract": False,
                    },
                ),
            ],
            # Table already exists. See wagtailio/utils/migrations/0002_auto_20220802_1706.py
            database_operations=[],
        ),
    ]
