# Generated by Django 3.2.12 on 2022-08-18 16:12

from django.db import migrations

import wagtail.contrib.typed_table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_cta_block_text_not_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "rich_text",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "rich_text",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "h2",
                                            "h3",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document",
                                        ],
                                        required=True,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "text_and_media",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "embed",
                                    wagtail.embeds.blocks.EmbedBlock(required=False),
                                ),
                                (
                                    "image_on_right",
                                    wagtail.core.blocks.BooleanBlock(
                                        default=False, required=False
                                    ),
                                ),
                                (
                                    "heading",
                                    wagtail.core.blocks.TextBlock(required=True),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(required=True),
                                ),
                                (
                                    "cta",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.CharBlock(
                                                    label="CTA text",
                                                    max_length=255,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "cta_page",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    label="CTA page", required=False
                                                ),
                                            ),
                                            (
                                                "cta_url",
                                                wagtail.core.blocks.URLBlock(
                                                    label="CTA URL", required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "headline",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(max_length=255),
                                ),
                                (
                                    "sub_heading",
                                    wagtail.core.blocks.TextBlock(required=False),
                                ),
                                (
                                    "intro",
                                    wagtail.core.blocks.TextBlock(required=False),
                                ),
                                (
                                    "cta",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.CharBlock(
                                                    label="CTA text",
                                                    max_length=255,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "cta_page",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    label="CTA page", required=False
                                                ),
                                            ),
                                            (
                                                "cta_url",
                                                wagtail.core.blocks.URLBlock(
                                                    label="CTA URL", required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "icon",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("arrow", "Arrow"),
                                            ("arrow-alt", "Arrow alt"),
                                            ("arrow-in-circle", "Arrow in circle"),
                                            ("arrow-in-square", "Arrow in square"),
                                            ("arrows", "Arrows"),
                                            ("blog", "Blog"),
                                            ("bread", "Bread"),
                                            ("briefcase", "Briefcase"),
                                            ("building", "Building"),
                                            ("calendar", "Calendar"),
                                            ("document", "Document"),
                                            ("envelope", "Envelope"),
                                            ("explanation", "Explanation"),
                                            ("eye", "Eye"),
                                            ("flame", "Flame"),
                                            ("friends", "Friends"),
                                            ("github", "Github"),
                                            ("handshake", "Handshake"),
                                            ("heart", "Heart"),
                                            ("history", "History"),
                                            ("id-card", "ID Card"),
                                            ("image", "Image"),
                                            ("knife-fork", "Knife Fork"),
                                            ("leaf", "Leaf"),
                                            ("location-pin", "Location Pin"),
                                            ("map", "Map"),
                                            ("money", "Money"),
                                            ("moon", "Moon"),
                                            ("one-two-steps", "One Two Steps"),
                                            ("padlock-dark", "Padlock Dark"),
                                            ("padlock-light", "Padlock Light"),
                                            ("paper-plane", "Paper Plane"),
                                            ("paper-stack", "Paper Stack"),
                                            ("pen-checkbox", "Pen Checkbox"),
                                            ("person-in-tie", "Person in Tie"),
                                            ("python", "Python"),
                                            (
                                                "question-mark-circle",
                                                "Question Mark Circle",
                                            ),
                                            ("quotes", "Quotes"),
                                            ("release-cycle", "Release Cycle"),
                                            ("roadmap", "Roadmap"),
                                            ("rocket", "Rocket"),
                                            ("rollback", "Rollback"),
                                            ("slack", "Slack"),
                                            ("speech-bubble", "Speech Bubble"),
                                            ("sun-cloud-dark", "Sun Cloud Dark"),
                                            ("sun-cloud-light", "Sun Cloud Light"),
                                            ("table-tennis", "Table Tennis"),
                                            ("tree", "Tree"),
                                            ("wordpress", "Wordpress"),
                                            ("world", "World"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "dark_background",
                                    wagtail.core.blocks.BooleanBlock(
                                        default=False, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "highlight",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(max_length=100),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(required=False),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "image_on_right",
                                    wagtail.core.blocks.BooleanBlock(
                                        default=False, required=False
                                    ),
                                ),
                                (
                                    "meta_text",
                                    wagtail.core.blocks.CharBlock(
                                        max_length=50, required=False
                                    ),
                                ),
                                (
                                    "meta_icon",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("arrow", "Arrow"),
                                            ("arrow-alt", "Arrow alt"),
                                            ("arrow-in-circle", "Arrow in circle"),
                                            ("arrow-in-square", "Arrow in square"),
                                            ("arrows", "Arrows"),
                                            ("blog", "Blog"),
                                            ("bread", "Bread"),
                                            ("briefcase", "Briefcase"),
                                            ("building", "Building"),
                                            ("calendar", "Calendar"),
                                            ("document", "Document"),
                                            ("envelope", "Envelope"),
                                            ("explanation", "Explanation"),
                                            ("eye", "Eye"),
                                            ("flame", "Flame"),
                                            ("friends", "Friends"),
                                            ("github", "Github"),
                                            ("handshake", "Handshake"),
                                            ("heart", "Heart"),
                                            ("history", "History"),
                                            ("id-card", "ID Card"),
                                            ("image", "Image"),
                                            ("knife-fork", "Knife Fork"),
                                            ("leaf", "Leaf"),
                                            ("location-pin", "Location Pin"),
                                            ("map", "Map"),
                                            ("money", "Money"),
                                            ("moon", "Moon"),
                                            ("one-two-steps", "One Two Steps"),
                                            ("padlock-dark", "Padlock Dark"),
                                            ("padlock-light", "Padlock Light"),
                                            ("paper-plane", "Paper Plane"),
                                            ("paper-stack", "Paper Stack"),
                                            ("pen-checkbox", "Pen Checkbox"),
                                            ("person-in-tie", "Person in Tie"),
                                            ("python", "Python"),
                                            (
                                                "question-mark-circle",
                                                "Question Mark Circle",
                                            ),
                                            ("quotes", "Quotes"),
                                            ("release-cycle", "Release Cycle"),
                                            ("roadmap", "Roadmap"),
                                            ("rocket", "Rocket"),
                                            ("rollback", "Rollback"),
                                            ("slack", "Slack"),
                                            ("speech-bubble", "Speech Bubble"),
                                            ("sun-cloud-dark", "Sun Cloud Dark"),
                                            ("sun-cloud-light", "Sun Cloud Light"),
                                            ("table-tennis", "Table Tennis"),
                                            ("tree", "Tree"),
                                            ("wordpress", "Wordpress"),
                                            ("world", "World"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.CharBlock(
                                                    label="CTA text",
                                                    max_length=255,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "cta_page",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    label="CTA page", required=False
                                                ),
                                            ),
                                            (
                                                "cta_url",
                                                wagtail.core.blocks.URLBlock(
                                                    label="CTA URL", required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "teaser",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.core.blocks.PageChooserBlock(
                                        page_type=["blog.BlogPage"], required=False
                                    ),
                                ),
                                (
                                    "url_chooser",
                                    wagtail.core.blocks.URLBlock(required=False),
                                ),
                                (
                                    "image_for_external_link",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "heading_for_external_link",
                                    wagtail.core.blocks.TextBlock(required=False),
                                ),
                                (
                                    "subheading_for_ext_link",
                                    wagtail.core.blocks.TextBlock(
                                        label="Subheading for external link",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "icon_bullets",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "icon_bullets",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "icon",
                                                    wagtail.core.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("arrow", "Arrow"),
                                                            ("arrow-alt", "Arrow alt"),
                                                            (
                                                                "arrow-in-circle",
                                                                "Arrow in circle",
                                                            ),
                                                            (
                                                                "arrow-in-square",
                                                                "Arrow in square",
                                                            ),
                                                            ("arrows", "Arrows"),
                                                            ("blog", "Blog"),
                                                            ("bread", "Bread"),
                                                            ("briefcase", "Briefcase"),
                                                            ("building", "Building"),
                                                            ("calendar", "Calendar"),
                                                            ("document", "Document"),
                                                            ("envelope", "Envelope"),
                                                            (
                                                                "explanation",
                                                                "Explanation",
                                                            ),
                                                            ("eye", "Eye"),
                                                            ("flame", "Flame"),
                                                            ("friends", "Friends"),
                                                            ("github", "Github"),
                                                            ("handshake", "Handshake"),
                                                            ("heart", "Heart"),
                                                            ("history", "History"),
                                                            ("id-card", "ID Card"),
                                                            ("image", "Image"),
                                                            (
                                                                "knife-fork",
                                                                "Knife Fork",
                                                            ),
                                                            ("leaf", "Leaf"),
                                                            (
                                                                "location-pin",
                                                                "Location Pin",
                                                            ),
                                                            ("map", "Map"),
                                                            ("money", "Money"),
                                                            ("moon", "Moon"),
                                                            (
                                                                "one-two-steps",
                                                                "One Two Steps",
                                                            ),
                                                            (
                                                                "padlock-dark",
                                                                "Padlock Dark",
                                                            ),
                                                            (
                                                                "padlock-light",
                                                                "Padlock Light",
                                                            ),
                                                            (
                                                                "paper-plane",
                                                                "Paper Plane",
                                                            ),
                                                            (
                                                                "paper-stack",
                                                                "Paper Stack",
                                                            ),
                                                            (
                                                                "pen-checkbox",
                                                                "Pen Checkbox",
                                                            ),
                                                            (
                                                                "person-in-tie",
                                                                "Person in Tie",
                                                            ),
                                                            ("python", "Python"),
                                                            (
                                                                "question-mark-circle",
                                                                "Question Mark Circle",
                                                            ),
                                                            ("quotes", "Quotes"),
                                                            (
                                                                "release-cycle",
                                                                "Release Cycle",
                                                            ),
                                                            ("roadmap", "Roadmap"),
                                                            ("rocket", "Rocket"),
                                                            ("rollback", "Rollback"),
                                                            ("slack", "Slack"),
                                                            (
                                                                "speech-bubble",
                                                                "Speech Bubble",
                                                            ),
                                                            (
                                                                "sun-cloud-dark",
                                                                "Sun Cloud Dark",
                                                            ),
                                                            (
                                                                "sun-cloud-light",
                                                                "Sun Cloud Light",
                                                            ),
                                                            (
                                                                "table-tennis",
                                                                "Table Tennis",
                                                            ),
                                                            ("tree", "Tree"),
                                                            ("wordpress", "Wordpress"),
                                                            ("world", "World"),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "heading",
                                                    wagtail.core.blocks.CharBlock(
                                                        max_length=255
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.core.blocks.RichTextBlock(
                                                        features=[
                                                            "bold",
                                                            "italic",
                                                            "link",
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "cta",
                                                    wagtail.core.blocks.StructBlock(
                                                        [
                                                            (
                                                                "text",
                                                                wagtail.core.blocks.CharBlock(
                                                                    label="CTA text",
                                                                    max_length=255,
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "cta_page",
                                                                wagtail.core.blocks.PageChooserBlock(
                                                                    label="CTA page",
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "cta_url",
                                                                wagtail.core.blocks.URLBlock(
                                                                    label="CTA URL",
                                                                    required=False,
                                                                ),
                                                            ),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ],
                            icon="list-alt",
                        ),
                    ),
                    (
                        "cards",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "cards",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "heading",
                                                    wagtail.core.blocks.CharBlock(
                                                        max_length=255
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.core.blocks.RichTextBlock(
                                                        features=["bold", "italic"],
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "meta_icon",
                                                    wagtail.core.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("arrow", "Arrow"),
                                                            ("arrow-alt", "Arrow alt"),
                                                            (
                                                                "arrow-in-circle",
                                                                "Arrow in circle",
                                                            ),
                                                            (
                                                                "arrow-in-square",
                                                                "Arrow in square",
                                                            ),
                                                            ("arrows", "Arrows"),
                                                            ("blog", "Blog"),
                                                            ("bread", "Bread"),
                                                            ("briefcase", "Briefcase"),
                                                            ("building", "Building"),
                                                            ("calendar", "Calendar"),
                                                            ("document", "Document"),
                                                            ("envelope", "Envelope"),
                                                            (
                                                                "explanation",
                                                                "Explanation",
                                                            ),
                                                            ("eye", "Eye"),
                                                            ("flame", "Flame"),
                                                            ("friends", "Friends"),
                                                            ("github", "Github"),
                                                            ("handshake", "Handshake"),
                                                            ("heart", "Heart"),
                                                            ("history", "History"),
                                                            ("id-card", "ID Card"),
                                                            ("image", "Image"),
                                                            (
                                                                "knife-fork",
                                                                "Knife Fork",
                                                            ),
                                                            ("leaf", "Leaf"),
                                                            (
                                                                "location-pin",
                                                                "Location Pin",
                                                            ),
                                                            ("map", "Map"),
                                                            ("money", "Money"),
                                                            ("moon", "Moon"),
                                                            (
                                                                "one-two-steps",
                                                                "One Two Steps",
                                                            ),
                                                            (
                                                                "padlock-dark",
                                                                "Padlock Dark",
                                                            ),
                                                            (
                                                                "padlock-light",
                                                                "Padlock Light",
                                                            ),
                                                            (
                                                                "paper-plane",
                                                                "Paper Plane",
                                                            ),
                                                            (
                                                                "paper-stack",
                                                                "Paper Stack",
                                                            ),
                                                            (
                                                                "pen-checkbox",
                                                                "Pen Checkbox",
                                                            ),
                                                            (
                                                                "person-in-tie",
                                                                "Person in Tie",
                                                            ),
                                                            ("python", "Python"),
                                                            (
                                                                "question-mark-circle",
                                                                "Question Mark Circle",
                                                            ),
                                                            ("quotes", "Quotes"),
                                                            (
                                                                "release-cycle",
                                                                "Release Cycle",
                                                            ),
                                                            ("roadmap", "Roadmap"),
                                                            ("rocket", "Rocket"),
                                                            ("rollback", "Rollback"),
                                                            ("slack", "Slack"),
                                                            (
                                                                "speech-bubble",
                                                                "Speech Bubble",
                                                            ),
                                                            (
                                                                "sun-cloud-dark",
                                                                "Sun Cloud Dark",
                                                            ),
                                                            (
                                                                "sun-cloud-light",
                                                                "Sun Cloud Light",
                                                            ),
                                                            (
                                                                "table-tennis",
                                                                "Table Tennis",
                                                            ),
                                                            ("tree", "Tree"),
                                                            ("wordpress", "Wordpress"),
                                                            ("world", "World"),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "meta_text",
                                                    wagtail.core.blocks.TextBlock(
                                                        max_length=50
                                                    ),
                                                ),
                                                (
                                                    "cta",
                                                    wagtail.core.blocks.StructBlock(
                                                        [
                                                            (
                                                                "text",
                                                                wagtail.core.blocks.CharBlock(
                                                                    label="CTA text",
                                                                    max_length=255,
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "cta_page",
                                                                wagtail.core.blocks.PageChooserBlock(
                                                                    label="CTA page",
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "cta_url",
                                                                wagtail.core.blocks.URLBlock(
                                                                    label="CTA URL",
                                                                    required=False,
                                                                ),
                                                            ),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ],
                            group="Cards",
                            icon="th-list",
                        ),
                    ),
                    (
                        "logo_cards",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "cards",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "heading",
                                                    wagtail.core.blocks.CharBlock(
                                                        max_length=255
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.core.blocks.RichTextBlock(
                                                        features=["bold", "italic"],
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "meta_icon",
                                                    wagtail.core.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("arrow", "Arrow"),
                                                            ("arrow-alt", "Arrow alt"),
                                                            (
                                                                "arrow-in-circle",
                                                                "Arrow in circle",
                                                            ),
                                                            (
                                                                "arrow-in-square",
                                                                "Arrow in square",
                                                            ),
                                                            ("arrows", "Arrows"),
                                                            ("blog", "Blog"),
                                                            ("bread", "Bread"),
                                                            ("briefcase", "Briefcase"),
                                                            ("building", "Building"),
                                                            ("calendar", "Calendar"),
                                                            ("document", "Document"),
                                                            ("envelope", "Envelope"),
                                                            (
                                                                "explanation",
                                                                "Explanation",
                                                            ),
                                                            ("eye", "Eye"),
                                                            ("flame", "Flame"),
                                                            ("friends", "Friends"),
                                                            ("github", "Github"),
                                                            ("handshake", "Handshake"),
                                                            ("heart", "Heart"),
                                                            ("history", "History"),
                                                            ("id-card", "ID Card"),
                                                            ("image", "Image"),
                                                            (
                                                                "knife-fork",
                                                                "Knife Fork",
                                                            ),
                                                            ("leaf", "Leaf"),
                                                            (
                                                                "location-pin",
                                                                "Location Pin",
                                                            ),
                                                            ("map", "Map"),
                                                            ("money", "Money"),
                                                            ("moon", "Moon"),
                                                            (
                                                                "one-two-steps",
                                                                "One Two Steps",
                                                            ),
                                                            (
                                                                "padlock-dark",
                                                                "Padlock Dark",
                                                            ),
                                                            (
                                                                "padlock-light",
                                                                "Padlock Light",
                                                            ),
                                                            (
                                                                "paper-plane",
                                                                "Paper Plane",
                                                            ),
                                                            (
                                                                "paper-stack",
                                                                "Paper Stack",
                                                            ),
                                                            (
                                                                "pen-checkbox",
                                                                "Pen Checkbox",
                                                            ),
                                                            (
                                                                "person-in-tie",
                                                                "Person in Tie",
                                                            ),
                                                            ("python", "Python"),
                                                            (
                                                                "question-mark-circle",
                                                                "Question Mark Circle",
                                                            ),
                                                            ("quotes", "Quotes"),
                                                            (
                                                                "release-cycle",
                                                                "Release Cycle",
                                                            ),
                                                            ("roadmap", "Roadmap"),
                                                            ("rocket", "Rocket"),
                                                            ("rollback", "Rollback"),
                                                            ("slack", "Slack"),
                                                            (
                                                                "speech-bubble",
                                                                "Speech Bubble",
                                                            ),
                                                            (
                                                                "sun-cloud-dark",
                                                                "Sun Cloud Dark",
                                                            ),
                                                            (
                                                                "sun-cloud-light",
                                                                "Sun Cloud Light",
                                                            ),
                                                            (
                                                                "table-tennis",
                                                                "Table Tennis",
                                                            ),
                                                            ("tree", "Tree"),
                                                            ("wordpress", "Wordpress"),
                                                            ("world", "World"),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "meta_text",
                                                    wagtail.core.blocks.TextBlock(
                                                        max_length=50
                                                    ),
                                                ),
                                                (
                                                    "logo",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "cta_page",
                                                    wagtail.core.blocks.PageChooserBlock(
                                                        label="CTA page", required=False
                                                    ),
                                                ),
                                                (
                                                    "cta_url",
                                                    wagtail.core.blocks.URLBlock(
                                                        label="CTA URL", required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ],
                            group="Cards",
                            icon="images",
                        ),
                    ),
                    (
                        "cta",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.core.blocks.CharBlock(
                                        label="CTA text", max_length=255, required=False
                                    ),
                                ),
                                (
                                    "cta_page",
                                    wagtail.core.blocks.PageChooserBlock(
                                        label="CTA page", required=False
                                    ),
                                ),
                                (
                                    "cta_url",
                                    wagtail.core.blocks.URLBlock(
                                        label="CTA URL", required=False
                                    ),
                                ),
                            ],
                            group="Call to action",
                        ),
                    ),
                    (
                        "standalone_cta",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "cta",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.CharBlock(
                                                    label="CTA text",
                                                    max_length=255,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "cta_page",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    label="CTA page", required=False
                                                ),
                                            ),
                                            (
                                                "cta_url",
                                                wagtail.core.blocks.URLBlock(
                                                    label="CTA URL", required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        label="Short description",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Call to action",
                        ),
                    ),
                    (
                        "standalone_quote",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("quote", wagtail.core.blocks.TextBlock(required=True)),
                                (
                                    "author",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=["link"], required=True
                                    ),
                                ),
                                (
                                    "author_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                            ],
                            group="Quotes",
                        ),
                    ),
                    (
                        "multiple_quotes",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.TextBlock(required=True),
                                ),
                                (
                                    "quotes",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "quote",
                                                    wagtail.core.blocks.TextBlock(
                                                        required=True
                                                    ),
                                                ),
                                                (
                                                    "author",
                                                    wagtail.core.blocks.RichTextBlock(
                                                        features=["link"], required=True
                                                    ),
                                                ),
                                                (
                                                    "author_image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ]
                                        ),
                                        min_num=2,
                                    ),
                                ),
                            ],
                            group="Quotes",
                        ),
                    ),
                    (
                        "get_started_block",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            "core.GetStartedSnippet", icon="th-list"
                        ),
                    ),
                    (
                        "sign_up_form",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            "core.SignupFormSnippet", icon="envelope-open-text"
                        ),
                    ),
                    (
                        "comparison_table",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "comparison_table",
                                    wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                                        [
                                            (
                                                "content",
                                                wagtail.core.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "rich_text",
                                                            wagtail.core.blocks.RichTextBlock(
                                                                features=[
                                                                    "bold",
                                                                    "italic",
                                                                    "link",
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ],
                                                    max_num=1,
                                                    required=False,
                                                ),
                                            )
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
