# Generated by Django 5.1.4 on 2025-02-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_contentpage_body_alter_homepage_body'),
    ]

    operations = [
    ]
