# Generated by Django 5.1.5 on 2025-01-24 22:38

from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from wagtail.models import ReferenceIndex


def delete_tagget_references(apps, schema_editor):
    tagged_item_type = ContentType.objects.get(app_label="taggit", model="taggeditem")
    refs = ReferenceIndex.objects.filter(content_type=tagged_item_type)
    refs.delete()


class Migration(migrations.Migration):
    """
    We have references to TaggedItems in this project's ReferenceIndex. Wagtail no longer adds these
    items to the ReferenceIndex and we don't need them. This migration removes them.
    """

    dependencies = [
        ("core", "0061_remove_excess_tables"),
    ]

    operations = [
        migrations.RunPython(
            delete_tagget_references,
            migrations.RunPython.noop,
        )
    ]
