# Generated by Django 6.1.1 on 2026-09-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_add_wide_image_block"),
        ("images", "0017_drop_obsolete_alternative_text"),
        ("wagtailcore", "0098_apitoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationSchemaSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="One or two sentences on what the organisation does",
                    ),
                ),
                (
                    "same_as",
                    models.TextField(
                        blank=True,
                        help_text="Full URLs of official profiles (GitHub, LinkedIn, etc.), one per line",
                        verbose_name="Social profiles",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.wagtailioimage",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation schema",
            },
        ),
    ]
