# Generated by Django 6.1.1 on 2026-10-05 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_add_blog_highlights_block"),
        ("core", "0064_add_event_highlight_block"),
    ]

    operations = []
