# Generated by Django 1.9 on 2016-01-22 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import wagtail.images.models

import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailioimage",
            name="file_size",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="wagtailioimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="wagtailioimage",
            name="file",
            field=models.ImageField(
                height_field="height",
                upload_to=wagtail.images.models.get_upload_to,
                verbose_name="file",
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="wagtailioimage",
            name="height",
            field=models.IntegerField(editable=False, verbose_name="height"),
        ),
        migrations.AlterField(
            model_name="wagtailioimage",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text=None,
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="tags",
            ),
        ),
        migrations.AlterField(
            model_name="wagtailioimage",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="wagtailioimage",
            name="uploaded_by_user",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploaded by user",
            ),
        ),
        migrations.AlterField(
            model_name="wagtailioimage",
            name="width",
            field=models.IntegerField(editable=False, verbose_name="width"),
        ),
    ]
