# Generated by Django 1.9.8 on 2016-11-01 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_auto_20160727_1108"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailiorendition",
            name="filter_spec",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
