# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-01 12:49
from __future__ import unicode_literals

from django.db import migrations

from wagtail.images.utils import get_fill_filter_spec_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_upgrade_to_wagtail17_schema'),
    ]

    forward, reverse = get_fill_filter_spec_migrations('images', 'WagtailIORendition')
    operations = [
        migrations.RunPython(forward, reverse),
    ]
