# Generated by Django 1.9.8 on 2016-11-01 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0005_upgrade_to_wagtail17_schema"),
    ]

    operations = []
