# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-22 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_upgrade_to_wagtail18'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wagtailiorendition',
            name='filter',
        ),
        migrations.AlterField(
            model_name='wagtailiorendition',
            name='focal_point_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
    ]
