# Generated by Django 2.0.13 on 2019-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0008_upgrade_to_wagtail19"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtailioimage",
            name="file_hash",
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
    ]
