# Generated by Django 3.2.16 on 2022-10-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0010_add_duplicatefindingmixin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wagtailioimage",
            name="file_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=40
            ),
        ),
    ]
