# Generated by Django 4.2.8 on 2023-12-08 18:07

from django.db import migrations

import wagtail.images.models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0013_wagtail_42"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wagtailiorendition",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
    ]
