# Generated by Django 5.0.9 on 2024-11-14 13:14

from django.db import migrations


def forwards(apps, schema_editor):
    WagtailIOImage = apps.get_model("images", "WagtailIOImage")

    # For each image that has an alternative text, copy it to the description field
    # We can reasonably assume this will be good quality alt text.
    for image in WagtailIOImage.objects.exclude(alternative_text="").iterator():
        image.description = image.alternative_text
        image.save()


def backwards(apps, schema_editor):
    WagtailIOImage = apps.get_model("images", "WagtailIOImage")
    for image in WagtailIOImage.objects.exclude(description="").iterator():
        image.alternative_text = image.description
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0015_wagtailioimage_description"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards, elidable=True),
    ]
