# Generated by Django 5.0.9 on 2024-11-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0016_copy_alternative_text_to_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wagtailioimage",
            name="alternative_text",
        ),
    ]
