# Generated by Django 5.2.5 on 2025-08-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sitewide_alert", "0002_style_fields"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitewidealertsettings",
            name="cta_button_link",
            field=models.URLField(blank=True, verbose_name="CTA Link"),
        ),
        migrations.AddField(
            model_name="sitewidealertsettings",
            name="cta_button_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="sitewidealertsettings",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=50, verbose_name="CTA Text"),
        ),
    ]
