# Generated by Django 5.2.5 on 2025-08-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sitewide_alert", "0003_sitewidealertsettings_add_cta"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitewidealertsettings",
            name="cta_button_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="CTA Page",
            ),
        ),
    ]
