# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 13:29
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20160729_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('primary_features', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('introduction', wagtail.wagtailcore.blocks.RichTextBlock()), ('features', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailsnippets.blocks.SnippetChooserBlock('features.FeatureDescription'))), ('links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock()), ('link_text_bold', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('link_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.wagtailcore.blocks.CharBlock(required=False))))))))), ('additional_features', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('features_groups', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock()), ('features', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.RichTextBlock()))))))))))))), default={}),
            preserve_default=False,
        ),
    ]
