# Generated by Django 1.9.8 on 2016-11-10 13:29

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0002_auto_20160729_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                (
                    (
                        "primary_features",
                        wagtail.blocks.StructBlock(
                            (
                                ("title", wagtail.blocks.CharBlock()),
                                ("introduction", wagtail.blocks.RichTextBlock()),
                                (
                                    "features",
                                    wagtail.blocks.ListBlock(
                                        wagtail.snippets.blocks.SnippetChooserBlock(
                                            "features.FeatureDescription"
                                        )
                                    ),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            (
                                                (
                                                    "link_text",
                                                    wagtail.blocks.CharBlock(),
                                                ),
                                                (
                                                    "link_text_bold",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "link_page",
                                                    wagtail.blocks.PageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "link_url",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                            )
                                        )
                                    ),
                                ),
                            )
                        ),
                    ),
                    (
                        "additional_features",
                        wagtail.blocks.StructBlock(
                            (
                                ("title", wagtail.blocks.CharBlock()),
                                (
                                    "features_groups",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            (
                                                (
                                                    "name",
                                                    wagtail.blocks.CharBlock(),
                                                ),
                                                (
                                                    "features",
                                                    wagtail.blocks.ListBlock(
                                                        wagtail.blocks.StructBlock(
                                                            (
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(),
                                                                ),
                                                                (
                                                                    "text",
                                                                    wagtail.blocks.RichTextBlock(),
                                                                ),
                                                            )
                                                        )
                                                    ),
                                                ),
                                            )
                                        )
                                    ),
                                ),
                            )
                        ),
                    ),
                ),
                default={},
            ),
            preserve_default=False,
        ),
    ]
