# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-01 14:50
from __future__ import unicode_literals

from django.db import migrations


# We need to remove all feature pages before deleting FeaturePage model
# to cleanup the wagtailcore_page table
# Will be great to run ./manage.py fixtree
def remove_feature_pages(apps, schema_editor):
    FeaturePage = apps.get_model('features', 'FeaturePage')

    FeaturePage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('features', '0005_featureaspect_video_url'),
    ]

    operations = [
        migrations.RunPython(remove_feature_pages),
        migrations.RemoveField(
            model_name='featurepage',
            name='listing_image',
        ),
        migrations.RemoveField(
            model_name='featurepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='featurepage',
            name='social_image',
        ),
        migrations.RemoveField(
            model_name='featurepagefeatureaspect',
            name='feature_aspect',
        ),
        migrations.RemoveField(
            model_name='featurepagefeatureaspect',
            name='page',
        ),
        migrations.DeleteModel(
            name='FeaturePage',
        ),
        migrations.DeleteModel(
            name='FeaturePageFeatureAspect',
        ),
    ]
