# Generated by Django 2.2.13 on 2020-10-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0008_auto_20180604_1605"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredescription",
            name="airtable_record_id",
            field=models.CharField(blank=True, db_index=True, max_length=35),
        ),
    ]
