# Generated by Django 3.2.12 on 2022-08-24 11:57

import django.db.models.deletion
from django.db import migrations, models

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_update_svg_icon_list"),
        ("features", "0010_featureaspect_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featureindexpage",
            name="body",
        ),
        migrations.AddField(
            model_name="featureindexpage",
            name="cta",
            field=wagtail.fields.StreamField(
                [
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="CTA text",
                                                    max_length=255,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "cta_page",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="CTA page", required=False
                                                ),
                                            ),
                                            (
                                                "cta_url",
                                                wagtail.blocks.URLBlock(
                                                    label="CTA URL", required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(
                                        label="Short description",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="featureindexpage",
            name="features",
            field=wagtail.fields.StreamField(
                [
                    (
                        "features",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "blocks",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "heading",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=255, required=False
                                                    ),
                                                ),
                                                (
                                                    "features",
                                                    wagtail.blocks.ListBlock(
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "heading",
                                                                    wagtail.blocks.CharBlock(
                                                                        label="Feature heading",
                                                                        max_length=255,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        features=[
                                                                            "bold",
                                                                            "italic",
                                                                            "link",
                                                                            "document",
                                                                        ],
                                                                        label="Feature description",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "link",
                                                                    wagtail.blocks.URLBlock(
                                                                        label="Feature link",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "link_title",
                                                                    wagtail.blocks.CharBlock(
                                                                        default="View docs",
                                                                        label="Feature link title",
                                                                        max_length=50,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                        min_num=2,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="featureindexpage",
            name="get_started",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.getstartedsnippet",
            ),
        ),
        migrations.AddField(
            model_name="featureindexpage",
            name="subheading",
            field=models.TextField(blank=True, verbose_name="Sub heading"),
        ),
    ]
