# Generated by Django 3.2.12 on 2022-08-18 17:40

import django.db.models.deletion
from django.db import migrations, models

import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_add_get_started_and_signup_snippets_and_alter_contentpage_body"),
        ("features", "0010_featureaspect_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureindexpage",
            name="cta",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "cta",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "cta_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="CTA text", max_length=255
                                    ),
                                ),
                                (
                                    "cta_page",
                                    wagtail.core.blocks.PageChooserBlock(
                                        label="CTA page", required=False
                                    ),
                                ),
                                (
                                    "cta_url",
                                    wagtail.core.blocks.URLBlock(
                                        label="CTA URL", required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="featureindexpage",
            name="get_started",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.getstartedsnippet",
            ),
        ),
        migrations.AddField(
            model_name="featureindexpage",
            name="subheading",
            field=models.TextField(blank=True, verbose_name="Sub heading"),
        ),
        migrations.AlterField(
            model_name="featureindexpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "feature_category",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        max_length=255, required=False
                                    ),
                                ),
                                (
                                    "features",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "heading",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Feature heading",
                                                        max_length=255,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.core.blocks.RichTextBlock(
                                                        features=[
                                                            "bold",
                                                            "italic",
                                                            "link",
                                                            "document",
                                                        ],
                                                        label="Feature description",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "link",
                                                    wagtail.core.blocks.URLBlock(
                                                        label="Feature link",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "link_title",
                                                    wagtail.core.blocks.CharBlock(
                                                        default="View docs",
                                                        help_text="If left blank, 'View docs' will be used as the default Feature link title",
                                                        label="Feature link title",
                                                        max_length=50,
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        min_num=2,
                                    ),
                                ),
                            ]
                        ),
                    )
                ]
            ),
        ),
    ]
