# Generated by Django 1.9.8 on 2016-07-29 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="author",
            table=None,
        ),
        migrations.AlterModelTable(
            name="blogindexpage",
            table=None,
        ),
        migrations.AlterModelTable(
            name="blogpage",
            table=None,
        ),
    ]
