# Generated by Django 2.2.13 on 2020-10-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_auto_20190813_0931"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="airtable_record_id",
            field=models.CharField(blank=True, db_index=True, max_length=35),
        ),
    ]
