# Generated by Django 3.2.16 on 2022-10-05 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_streamfield_use_json_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="airtable_record_id",
        ),
    ]
