# Generated by Django 5.1.6 on 2025-03-27 03:50

from django.db import migrations, models
import django.db.models.deletion

import modelcluster.fields


def migrate_author_data(apps, schema_editor):
    BlogPage = apps.get_model("blog", "BlogPage")
    BlogPageAuthor = apps.get_model("blog", "BlogPageAuthor")

    for blog_page in BlogPage.objects.all():
        if blog_page.author:
            BlogPageAuthor.objects.create(
                page=blog_page, author=blog_page.author, sort_order=0
            )


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_add_new_imageblock"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPageAuthor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="blog.author",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="blog.blogpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.RunPython(migrate_author_data),
        migrations.RemoveField(
            model_name="blogpage",
            name="author",
        ),
    ]
