# Generated by Django 5.2 on 2025-05-07 21:17
# Needed to add null=True to the date field in BlogPage model so deferred validation functions properly

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_add_new_imageblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
