# Generated by Django 6.1.1 on 2026-10-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_remove_blogpage_author_blogpageauthor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date",
            field=models.DateField(),
        ),
    ]
