# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0002_update_to_wagtail_13'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the parent organisation using Wagtail (e.g. NASA)', max_length=100)),
                ('description', models.TextField(blank=True, help_text="This currently isn't being shown on the site, but may be in the future")),
                ('URL', models.URLField(blank=True, help_text="This currently isn't being show on the site, but may be in the future")),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.WagtailIOImage')),
            ],
        ),
    ]
