# Generated by Django 1.9.8 on 2016-07-28 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("standardpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="standardpage",
            table=None,
        ),
    ]
