# Generated by Django 5.1.6 on 2025-05-07 11:40

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("standardpage", "0009_add_new_imageblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("h2", 0),
                    ("h3", 1),
                    ("h4", 2),
                    ("paragraph", 3),
                    ("blockquote", 4),
                    ("image", 5),
                    ("document", 6),
                    ("embed", 7),
                    ("markdown", 8),
                    ("codeblock", 11),
                    ("teaser", 17),
                    ("get_started_block", 18),
                    ("sign_up_form", 19),
                    ("highlight", 28),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "description": "A level 2 heading",
                            "form_classname": "title",
                            "icon": "title",
                            "preview_value": "The joy of heading level 2",
                            "template": "patterns/components/streamfields/headings/heading-2.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "description": "A level 3 heading",
                            "form_classname": "title",
                            "icon": "title",
                            "preview_value": "The joy of heading level 3",
                            "template": "patterns/components/streamfields/headings/heading-3.html",
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "description": "A level 4 heading",
                            "form_classname": "title",
                            "icon": "title",
                            "preview_value": "The joy of heading level 4",
                            "template": "patterns/components/streamfields/headings/heading-4.html",
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "description": "A rich text paragraph",
                            "icon": "pilcrow",
                            "preview_value": 'The Wagtail bird is the mascot of <a href="https://wagtail.org">Wagtail</a>, a <i>free</i> and <b>open-source</b> content management system (CMS) built on Django.',
                            "template": "patterns/components/streamfields/rich_text_block/rich_text_block.html",
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "description": "A blockquote",
                            "form_classname": "title",
                            "icon": "openquote",
                            "preview_value": "Wagtail is such a great CMS that I love using.",
                            "template": "patterns/components/streamfields/quotes/standalone_quote_block.html",
                        },
                    ),
                    5: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "icon": "image",
                            "template": "patterns/components/streamfields/image/image.html",
                        },
                    ),
                    6: (
                        "wagtailio.utils.blocks.CustomDocumentBlock",
                        (),
                        {
                            "icon": "doc-full-inverse",
                            "template": "patterns/components/streamfields/document/document.html",
                        },
                    ),
                    7: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "description": "An embedded video or other media",
                            "icon": "code",
                            "preview_value": "https://www.youtube.com/watch?v=t0H1yM1FWZY",
                            "template": "patterns/components/streamfields/embed/embed.html",
                        },
                    ),
                    8: (
                        "wagtailio.utils.blocks.MarkDownBlock",
                        (),
                        {
                            "template": "patterns/components/streamfields/code_block/code_block.html"
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("django", "Django templating language"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                            ]
                        },
                    ),
                    10: ("wagtail.blocks.TextBlock", (), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 9), ("code", 10)]],
                        {
                            "template": "patterns/components/streamfields/code_block/code_block.html"
                        },
                    ),
                    12: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["blog.BlogPage"], "required": False},
                    ),
                    13: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    14: ("wagtail.images.blocks.ImageBlock", [], {}),
                    15: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Subheading for external link", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 12),
                                ("url_chooser", 13),
                                ("image_for_external_link", 14),
                                ("heading_for_external_link", 15),
                                ("subheading_for_ext_link", 16),
                            ]
                        ],
                        {"group": "CTA options"},
                    ),
                    18: (
                        "wagtailio.utils.blocks.CustomSnippetBlock",
                        ("core.GetStartedSnippet",),
                        {
                            "description": "A set of links to get started with Wagtail",
                            "group": "CTA options",
                            "icon": "table-list",
                            "template": "patterns/components/streamfields/get_started_block/get_started_block.html",
                        },
                    ),
                    19: (
                        "wagtailio.utils.blocks.CustomSnippetBlock",
                        ("core.SignupFormSnippet",),
                        {
                            "description": "A form to sign up for a newsletter or other service",
                            "group": "CTA options",
                            "icon": "envelope-open-text",
                            "template": "patterns/components/streamfields/sign_up_form_block/sign_up_form_block.html",
                        },
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": False},
                    ),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("arrow-alt", "Arrow alt"),
                                ("arrow-in-circle", "Arrow in circle"),
                                ("arrow-in-square", "Arrow in square"),
                                ("arrows", "Arrows"),
                                ("blog", "Blog"),
                                ("bread", "Bread"),
                                ("briefcase", "Briefcase"),
                                ("building", "Building"),
                                ("calendar", "Calendar"),
                                ("code-file", "Code File"),
                                ("document", "Document"),
                                ("envelope", "Envelope"),
                                ("explanation", "Explanation"),
                                ("eye", "Eye"),
                                ("flame", "Flame"),
                                ("friends", "Friends"),
                                ("github", "Github"),
                                ("handshake", "Handshake"),
                                ("heart", "Heart"),
                                ("history", "History"),
                                ("id-card", "ID Card"),
                                ("image", "Image"),
                                ("knife-fork", "Knife Fork"),
                                ("leaf", "Leaf"),
                                ("location-pin", "Location Pin"),
                                ("map", "Map"),
                                ("magnifying-glass", "Magnifying Glass"),
                                ("money", "Money"),
                                ("moon", "Moon"),
                                ("one-two-steps", "One Two Steps"),
                                ("padlock", "Padlock"),
                                ("paper-plane", "Paper Plane"),
                                ("paper-stack", "Paper Stack"),
                                ("pen-checkbox", "Pen Checkbox"),
                                ("person-in-tie", "Person in Tie"),
                                ("python", "Python"),
                                ("question-mark-circle", "Question Mark Circle"),
                                ("quotes", "Quotes"),
                                ("release-cycle", "Release Cycle"),
                                ("roadmap", "Roadmap"),
                                ("rocket", "Rocket"),
                                ("rollback", "Rollback"),
                                ("slack", "Slack"),
                                ("speech-bubble", "Speech Bubble"),
                                ("sun-cloud", "Sun Cloud"),
                                ("table-tennis", "Table Tennis"),
                                ("tree", "Tree"),
                                ("wordpress", "Wordpress"),
                                ("world", "World"),
                            ],
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "CTA text", "max_length": 255, "required": False},
                    ),
                    25: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "CTA page", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "CTA URL", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 24), ("cta_page", 25), ("cta_url", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 20),
                                ("description", 15),
                                ("image", 14),
                                ("image_on_right", 21),
                                ("meta_text", 22),
                                ("meta_icon", 23),
                                ("cta", 27),
                            ]
                        ],
                        {
                            "description": "A block of highlighted text with a heading, description, and an optional image"
                        },
                    ),
                },
            ),
        ),
    ]
