# Generated by Django 3.2.18 on 2024-01-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showcase", "0002_populate_sectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="showcasepage",
            name="listing_meta_description",
            field=models.CharField(
                blank=True,
                help_text="The description beneath the listing",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="showcaseitem",
            name="description",
            field=models.TextField(),
        ),
    ]
