# Generated by Django 4.2.8 on 2024-03-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showcase", "0003_remove_showcasepage_listing_meta_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showcaseitem",
            name="alt_text",
            field=models.CharField(max_length=255),
        ),
    ]
