# Generated by Django 6.0.2 on 2026-03-11 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0017_drop_obsolete_alternative_text"),
        ("showcase", "0004_alter_showcaseitem_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showcaseitem",
            name="image",
            field=models.ForeignKey(
                help_text="Image ratio: 3:2 (e.g., 600 X 400px)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.wagtailioimage",
            ),
        ),
    ]
